// Simplified English-only context (no language switching)
import React, { createContext, useContext, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en';
  setLanguage: (lang: 'en') => void;
  t: any; // English translations object
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simplified English-only translations
const englishTranslations = {
  companyName: 'FUJIAN COSUN TUFF BUILDING MATERIALS CO., LTD.',
  companyNameEn: 'YOUR ONE-STOP SOURCING SOLUTION EXPERT IN CHINA',
  header: {
    home: 'Home',
    projectSolution: 'Project Solution',
    qcmaster: 'Your QC Expert',
    shipmenthub: 'Shipment Hub',
    specials: 'Special & Offers',
    products: 'Products',
  },
  hero: {
    slide1Title: 'Leading Building Materials Manufacturer',
    slide1Subtitle: 'Committed to providing high-quality building material solutions',
    slide2Title: 'Quality Products Focused on Innovation',
    slide2Subtitle: 'Advanced production technology, strict quality control',
    slide3Title: 'Global Service Network',
    slide3Subtitle: 'Professional pre and post-sales support',
    learnMore: 'Learn More',
    contactUs: 'Contact Us',
  },
  latestProducts: {
    badge: 'Latest Products',
    title: 'Discover Our Latest Innovations',
    subtitle: 'Watch our product demonstrations and discover how our building materials can transform your projects',
    product1Title: 'Premium Steel Roofing Sheets',
    product1Desc: 'High-quality galvanized steel sheets with superior weather resistance',
    product1Feature1: 'Anti-corrosion coating',
    product1Feature2: '50-year warranty',
    product1Feature3: 'Easy installation',
    product2Title: 'Eco-Friendly Insulation Panels',
    product2Desc: 'Energy-efficient panels with excellent thermal performance',
    product2Feature1: 'R-30+ value',
    product2Feature2: 'Fire resistant',
    product2Feature3: 'Moisture resistant',
    product3Title: 'Modular Wall Systems',
    product3Desc: 'Flexible wall solutions for rapid construction projects',
    product3Feature1: 'Quick assembly',
    product3Feature2: 'Customizable design',
    product3Feature3: 'Lightweight yet durable',
    learnMore: 'Learn More',
    ctaTitle: 'Want to See More Product Demonstrations?',
    ctaDesc: 'Contact our team to schedule a personalized product presentation or visit our showroom',
    contactButton: 'Contact Sales Team',
    catalogButton: 'Download Complete Catalog',
  },
  products: {
    title: 'Product Center',
    subtitle: 'Discover our comprehensive range of high-quality building materials',
    all: 'All Products',
    viewDetails: 'View Details',
    addToCart: 'Add to Cart',
    categories: {
      appliances: 'Appliances',
      bath: 'Bath',
      buildingMaterials: 'Building Materials',
      decorFurniture: 'Decor & Furniture',
      electrical: 'Electrical',
      flooring: 'Flooring',
      hardware: 'Hardware',
      heatingCooling: 'Heating & Cooling',
      kitchen: 'Kitchen',
      lawnGarden: 'Lawn & Garden',
      lighting: 'Lighting & Fans',
      outdoorLiving: 'Outdoor Living',
      paint: 'Paint',
      plumbing: 'Plumbing',
      storage: 'Storage & Organization',
      tools: 'Tools',
      windowsDoors: 'Windows & Doors',
    },
  },
  qcMaster: {
    title: 'Your Eyes in The Supply Chain',
    subtitle: 'Professional third-party quality inspection services to ensure your products meet international standards',
    featuresTitle: 'Why Choose Our QC Services',
    features: {
      comprehensive: 'Comprehensive Inspection',
      comprehensiveDesc: 'Full-spectrum quality control from raw materials to final products',
      inspection: 'On-Site Inspection',
      inspectionDesc: 'Professional inspectors work directly at manufacturing facilities',
      documentation: 'Detailed Documentation',
      documentationDesc: 'Complete inspection reports with photos and measurements',
      team: 'Expert Team',
      teamDesc: 'Certified QC professionals with industry expertise',
    },
    servicesTitle: 'Our QC Services',
    services: {
      preProduction: 'Pre-Production Inspection',
      preProductionItems: {
        factoryAudit: 'Factory capability assessment',
        sampleApproval: 'Sample approval and verification',
        materialVerification: 'Raw material quality verification',
      },
      duringProduction: 'During Production Inspection',
      duringProductionItems: {
        processMonitoring: 'Production process monitoring',
        qualityChecks: 'In-line quality checks at critical stages',
        progressReports: 'Regular progress and quality reports',
      },
      preShipment: 'Pre-Shipment Inspection',
      preShipmentItems: {
        finalInspection: 'Final product inspection (100% or AQL sampling)',
        packagingVerification: 'Packaging and labeling verification',
        quantityCheck: 'Quantity verification and measurement',
      },
    },
    certificationsTitle: 'Our QC Expert Certifications',
    certificationName: 'AENOR Certified Dedicated Inspector',
    certificationDesc: 'Our QC inspectors are certified by AENOR (Spanish Association for Standardization and Certification)',
    expertiseTitle: 'Expertise Level',
    expertiseDesc: 'Certified professionals with years of industry experience',
    validityTitle: 'Certification Validity',
    validityDesc: 'Valid through 2025, regularly updated and renewed',
    whyCertificationTitle: 'Why This Matters to You',
    certificationBenefit1: 'Guaranteed compliance with international quality standards',
    certificationBenefit2: 'Systematic and thorough inspection processes',
    certificationBenefit3: 'Third-party validated expertise and credibility',
    teamInAction: 'Our QC Team in Action',
    standardsTitle: 'Quality Standards We Follow',
    benefitsTitle: 'Benefits of Our QC Services',
    benefits: {
      defectReduction: 'Defect Reduction',
      defectReductionDesc: 'Identify and resolve quality issues before shipment',
      compliance: 'Standards Compliance',
      complianceDesc: 'Ensure products meet international quality standards',
      transparency: 'Full Transparency',
      transparencyDesc: 'Detailed reports with complete traceability',
      riskMitigation: 'Risk Mitigation',
      riskMitigationDesc: 'Protect your investment and brand reputation',
    },
    ctaTitle: 'Need Quality Assurance for Your Order?',
    ctaDesc: 'Let our certified QC experts ensure your products meet the highest quality standards',
    ctaButton: 'Request QC Service',
  },
  qcServiceForm: {
    title: 'Request Quality Control Service',
    description: 'Fill out the form below and our QC experts will contact you within 24 hours',
    companyInfoTitle: 'Company Information',
    companyName: 'Company Name',
    companyNamePlaceholder: 'Enter your company name',
    contactName: 'Contact Person',
    contactNamePlaceholder: 'Enter contact person name',
    email: 'Email Address',
    emailPlaceholder: 'your.email@company.com',
    phone: 'Phone Number',
    phonePlaceholder: '+86 138 0000 0000',
    serviceRequirementsTitle: 'Service Requirements',
    specificRequirements: 'Specific Requirements',
    requirementsPlaceholder: 'Describe your specific QC requirements',
    inspectionFrequency: 'Monthly Inspection Frequency',
    selectFrequency: 'Select frequency',
    frequency1to5: '1-5 inspections/month',
    frequency6to10: '6-10 inspections/month',
    frequency11to20: '11-20 inspections/month',
    frequency20plus: '20+ inspections/month',
    urgency: 'Urgency Level',
    selectUrgency: 'Select urgency level',
    urgencyLow: 'Low - Within 2 weeks',
    urgencyMedium: 'Medium - Within 1 week',
    urgencyHigh: 'High - Within 3 days',
    urgencyUrgent: 'Urgent - ASAP',
    expectedDate: 'Expected Inspection Date',
    productCategories: 'Product Categories',
    qualityStandards: 'Quality Standards Required',
    additionalNotes: 'Additional Notes',
    additionalNotesPlaceholder: 'Any other information',
    cancel: 'Cancel',
    submit: 'Submit Request',
    validationError: 'Please fill in all required fields',
    submitSuccess: 'Request submitted successfully',
    successTitle: 'Request Submitted Successfully!',
    successMessage: 'Our QC experts will contact you within 24 hours',
  },
  shipmentHub: {
    title: 'Global Shipment Hub Solutions',
    subtitle: 'Streamline your logistics with comprehensive shipment consolidation services',
    tagline: 'From order to delivery - we handle every detail',
    shipmentCasesTitle: 'Real Shipment Cases',
    shipmentCasesDesc: 'See how we optimize container space',
    shipmentCase1: 'Multi-product consolidation reducing costs by 35%',
    shipmentCase2: 'Mixed SKU optimization achieving 98% utilization',
    shipmentCase3: 'Strategic loading maximizing capacity',
    capabilitiesTitle: 'Our Shipment Capabilities',
    capabilities: {
      manufacturers: 'Partner Manufacturers',
      manufacturersDesc: 'Access to over 1000 verified manufacturers',
      skuConsolidation: 'SKU Consolidation',
      skuConsolidationDesc: 'Combine multiple products efficiently',
      containerOptimization: 'Container Optimization',
      containerOptimizationDesc: 'Up to 95% space utilization',
      costSavings: 'Cost Savings',
      costSavingsDesc: 'Reduce shipping costs up to 30%',
    },
    featuresTitle: 'Shipment Hub Features',
    features: {
      multiSkuTitle: 'Multi-SKU Consolidation',
      multiSkuDesc: 'Combine products from multiple suppliers',
      multiSkuItems: {
        unlimited: 'Unlimited product combinations',
        tracking: 'Real-time tracking',
        quality: 'Quality control at every step',
      },
      containerTitle: 'Container Optimization',
      containerDesc: 'Maximize container space utilization',
      containerItems: {
        optimization: '3D loading optimization',
        mixedLoading: 'Mixed product loading',
        costEffective: 'Cost-effective selection',
      },
      shippingTitle: 'Global Shipping Network',
      shippingDesc: 'Worldwide shipping routes',
      shippingItems: {
        carrierSelection: 'Best carrier selection',
        rateNegotiation: 'Negotiated rates',
        scheduling: 'Flexible schedules',
      },
    },
    processTitle: 'Our Shipment Process',
    process: {
      orderReceiving: 'Order Receiving',
      orderReceivingDesc: 'Receive and process orders',
      supplierCoordination: 'Supplier Coordination',
      supplierCoordinationDesc: 'Coordinate with suppliers',
      consolidation: 'Product Consolidation',
      consolidationDesc: 'Consolidate at warehouses',
      containerLoading: 'Container Loading',
      containerLoadingDesc: 'Optimize loading with 3D planning',
      shipping: 'Global Shipping',
      shippingDesc: 'Ship via trusted carriers',
      delivery: 'Final Delivery',
      deliveryDesc: 'On-time delivery',
    },
    benefitsTitle: 'Shipment Hub Benefits',
    benefits: {
      costReduction: 'Cost Reduction',
      costReductionDesc: 'Save on shipping costs',
      efficiency: 'Efficiency',
      efficiencyDesc: 'Faster processing',
      network: 'Global Network',
      networkDesc: 'Extensive supplier network',
      shipping: 'Reliability',
      shippingDesc: 'On-time delivery',
    },
    ctaTitle: 'Ready to Optimize Your Shipments?',
    ctaDesc: 'Contact us for a free consultation',
    ctaButton: 'Get Shipment Quote',
  },
  services: {
    title: 'Our Services',
    subtitle: 'Comprehensive support for your building materials needs',
    consulting: 'Expert Consulting',
    consultingDesc: 'Professional guidance on material selection',
    customization: 'Custom Solutions',
    customizationDesc: 'Tailored products for your requirements',
    logistics: 'Global Logistics',
    logisticsDesc: 'Efficient worldwide shipping',
    afterSales: 'After-Sales Support',
    afterSalesDesc: '24/7 customer service',
    training: 'Training & Education',
    trainingDesc: 'Product training and guidance',
    warranty: 'Quality Warranty',
    warrantyDesc: 'Comprehensive warranty coverage',
  },
  news: {
    badge: 'Success Stories',
    title: 'Celebrating Our Successes and Learning from Failures',
    subtitle: 'We believe in transparency. Here we share achievements and lessons learned',
    successStoriesTitle: 'Our Success Stories',
    failureLessonsTitle: 'Lessons from Failures',
    success1: {
      title: 'Record Sales Achievement',
      description: 'Q2 2024 marked highest quarterly revenue',
      impact: '150% growth year-over-year',
    },
    success2: {
      title: 'Customer Satisfaction Milestone',
      description: 'Achieved 98% customer satisfaction rating',
      impact: '2,500+ positive reviews',
    },
    success3: {
      title: 'New Strategic Partnership',
      description: 'Partnered with major international distributors',
      impact: 'Expanded to 15 new markets',
    },
    success4: {
      title: 'Innovation Award',
      description: 'Received industry innovation award',
      impact: 'Leading the industry in sustainable materials',
    },
  },
  about: {
    title: 'Our Story',
    subtitle: 'Building Trust Through Quality and Transparency',
    mission: 'Our Mission',
    missionDesc: 'To provide world-class building materials with exceptional service',
    vision: 'Our Vision',
    visionDesc: 'To be the most trusted partner in global construction',
    values: 'Our Values',
    valuesDesc: 'Quality, integrity, and customer success',
    buyerConcernsTitle: 'How We Address Your Concerns',
    buyerConcern1: 'Quality Assurance',
    buyerConcern1Desc: 'Rigorous quality control at every stage',
    buyerConcern2: 'Competitive Pricing',
    buyerConcern2Desc: 'Direct factory prices, no middlemen',
    buyerConcern3: 'Reliable Delivery',
    buyerConcern3Desc: 'On-time delivery guaranteed',
    buyerConcern4: 'Product Variety',
    buyerConcern4Desc: 'Comprehensive product range',
    buyerConcern5: 'Documentation',
    buyerConcern5Desc: 'Complete certification and compliance',
    buyerConcern6: 'Support',
    buyerConcern6Desc: '24/7 customer service',
  },
  member: {
    title: 'Member Center',
    subtitle: 'Join our community for exclusive benefits',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    companyName: 'Company Name',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    loginButton: 'Sign In',
    registerButton: 'Create Account',
    benefits: {
      benefit1: 'Exclusive Discounts',
      benefit1Desc: 'Member-only pricing and promotions',
      benefit2: 'Priority Support',
      benefit2Desc: 'Dedicated customer service',
      benefit3: 'Special Offers',
      benefit3Desc: 'Early access to new products',
      benefit4: '24/7 Access',
      benefit4Desc: 'Round-the-clock support',
    },
  },
  login: {
    title: 'Customer Login Portal',
    subtitle: 'Access your account and manage orders',
    welcomeBack: 'Welcome Back',
    description: 'Sign in to access your dashboard',
    email: 'Email Address',
    emailPlaceholder: 'your.email@company.com',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot Password?',
    loginButton: 'Sign In',
    noAccount: "Don't have an account?",
    signUp: 'Sign up',
    orContinueWith: 'Or continue with',
    googleLogin: 'Continue with Google',
    features: {
      orders: 'Track Orders',
      ordersDesc: 'Real-time order tracking',
      quotes: 'Manage Quotes',
      quotesDesc: 'Request and review quotes',
      history: 'Order History',
      historyDesc: 'View past purchases',
      support: 'Priority Support',
      supportDesc: 'Direct customer service',
    },
  },
  supplier: {
    title: 'Become A Supplier',
    subtitle: 'Partner with us to reach global markets',
    formTitle: 'Supplier Registration',
    formDescription: 'Complete the form to start your partnership',
    companyInfo: 'Company Information',
    companyName: 'Company Name',
    companyNamePlaceholder: 'Enter company name',
    businessLicense: 'Business License Number',
    businessLicensePlaceholder: 'License number',
    contactInfo: 'Contact Information',
    contactName: 'Contact Person',
    contactNamePlaceholder: 'Full name',
    email: 'Email Address',
    emailPlaceholder: 'email@company.com',
    phone: 'Phone Number',
    phonePlaceholder: '+86 138 0000 0000',
    productInfo: 'Product Information',
    productCategories: 'Product Categories',
    productCategoriesPlaceholder: 'e.g., Building Materials, Hardware',
    productDescription: 'Product Description',
    productDescriptionPlaceholder: 'Describe your products',
    annualCapacity: 'Annual Production Capacity',
    annualCapacityPlaceholder: 'Units per year',
    certifications: 'Certifications',
    certificationsPlaceholder: 'ISO, CE, etc.',
    submit: 'Submit Application',
    cancel: 'Cancel',
    benefits: {
      title: 'Partner Benefits',
      benefit1: 'Global Reach',
      benefit1Desc: 'Access to international markets',
      benefit2: 'Marketing Support',
      benefit2Desc: 'Professional marketing assistance',
      benefit3: 'Fair Pricing',
      benefit3Desc: 'Competitive commission structure',
      benefit4: 'Growth Opportunities',
      benefit4Desc: 'Expand your business',
    },
  },
  projectSolution: {
    title: 'Turnkey Project Solutions',
    subtitle: 'Comprehensive project management from sourcing to delivery - We handle everything so you can focus on your business',
    projectsTitle: 'Featured Project Portfolio',
    projects: {
      cannabis: 'Cannabis Facility Construction',
      warehouse: 'Industrial Warehouse & Production Facility',
      manufacturing: 'Manufacturing Plant Development',
    },
    cannabisTitle: 'Cannabis Production Facility Project',
    cannabisDesc: 'Complete turnkey solution for a 50,000 sq ft cannabis production facility including HVAC systems, specialized lighting, security infrastructure, and regulatory-compliant construction materials.',
    processDiagram: 'Project Implementation Process',
    servicesTitle: 'Comprehensive Project Services',
    services: {
      procurement: 'Full Procurement Management',
      procurementDesc: 'Source all materials and equipment from verified suppliers with competitive pricing',
      quality: 'Quality Control & Compliance',
      qualityDesc: 'On-site inspections, compliance verification, and quality assurance throughout the project',
      logistics: 'End-to-End Logistics',
      logisticsDesc: 'Coordinate shipping, warehousing, and delivery to ensure on-time project completion',
      compliance: 'Regulatory Compliance',
      complianceDesc: 'Ensure all materials and processes meet local and international standards',
    },
    benefitsTitle: 'Why Choose Our Turnkey Solutions',
    benefits: {
      costReduction: 'Reduce procurement costs by 20-30% through our supplier network',
      timeEfficiency: 'Save weeks on project timelines with streamlined coordination',
      qualityAssurance: 'Guaranteed quality with third-party inspections at every stage',
      riskMitigation: 'Minimize project risks with comprehensive oversight and insurance',
      singleContact: 'Single point of contact for all procurement and logistics',
      expertiseAccess: 'Access our 15+ years of industry expertise and supplier relationships',
    },
    processTitle: 'Our 7-Step Project Process',
    process: {
      consultation: 'Initial Consultation',
      consultationDesc: 'Understand project requirements, timeline, and budget',
      contract: 'Sign Contract',
      contractDesc: 'Finalize agreement and establish project terms',
      engineering: 'Engineer Communication',
      engineeringDesc: 'Collaborate with engineers on technical specifications',
      fabricating: 'Fabricating',
      fabricatingDesc: 'Manufacturing and production of your materials',
      quality: 'FAT Inspection',
      qualityDesc: 'Conduct thorough inspections before shipment',
      logistics: 'Logistics Coordination',
      logisticsDesc: 'Arrange optimal shipping and delivery schedules',
      delivery: 'Final Delivery',
      deliveryDesc: 'Ensure on-time delivery and installation support',
    },
    whyChooseTitle: 'Why Leading Companies Choose Us',
    whyChoose: {
      experience: '15+ years managing complex international projects',
      turnkeyExperience: 'Successfully completed 200+ turnkey projects worldwide',
      network: 'Network of 1,000+ verified suppliers across China',
      efficiency: 'Average 25% reduction in project costs and timelines',
      reliability: '98% on-time delivery rate with full shipment insurance',
    },
    contactTitle: 'Start Your Project Today',
    contactDesc: 'Our team is ready to discuss your project requirements and provide a detailed proposal',
    contactButton: 'Request Project Consultation',
  },
  specialOffers: {
    title: 'Special Offers & Promotions',
    subtitle: 'Exclusive deals on premium building materials',
    videoPromotions: 'Video Promotions',
    textPromotions: 'Current Offers',
    allCategories: 'All Categories',
    appliances: 'Appliances',
    buildingMaterials: 'Building Materials',
    hardware: 'Hardware',
    electrical: 'Electrical',
    learnMore: 'Learn More',
    shopNow: 'Shop Now',
  },
  failureCases: {
    title: 'Learning from Our Failure Cases',
    subtitle: 'Transparency builds trust - Here are lessons we learned',
    badge: 'Failure Cases',
    case1: {
      title: 'Quality Control Gap',
      issue: 'Missed defects in batch inspection',
      impact: 'Customer dissatisfaction',
      lesson: 'Implemented stricter QC protocols',
    },
    case2: {
      title: 'Delivery Delay',
      issue: 'Logistics coordination failure',
      impact: 'Project timeline affected',
      lesson: 'Enhanced supplier coordination',
    },
    case3: {
      title: 'Communication Breakdown',
      issue: 'Specification misunderstanding',
      impact: 'Product rework required',
      lesson: 'Improved documentation process',
    },
    case4: {
      title: 'Inventory Management',
      issue: 'Stock shortage during peak season',
      impact: 'Lost sales opportunity',
      lesson: 'Better demand forecasting',
    },
  },
  productCatalog: {
    title: 'Product Catalog',
    subtitle: 'Browse our complete range of building materials',
    level1Title: 'Main Categories',
    level1Subtitle: 'Select a category to explore',
    level2Title: 'Sub-Categories',
    level2Subtitle: 'Choose a product line',
    level3Title: 'Products',
    level3Subtitle: 'View product details',
    backToCategories: 'Back to Categories',
    backToSubcategories: 'Back to Sub-Categories',
    viewProducts: 'View Products',
    productSpecs: 'Specifications',
    weight: 'Weight',
    dimensions: 'Dimensions',
    packaging: 'Packaging',
    addToCart: 'Add to Cart',
    requestQuote: 'Request Quote',
  },
  socialMedia: {
    title: 'Our Social Media',
    subtitle: 'Follow us for latest updates and insights',
    facebook: 'Facebook',
    instagram: 'Instagram',
    linkedin: 'LinkedIn',
    youtube: 'YouTube',
    followUs: 'Follow Us',
    latestPosts: 'Latest Posts',
  },
  footer: {
    description: 'Leading manufacturer of premium building materials with over 15 years of experience',
    quickLinks: 'Quick Links',
    products: 'Products',
    services: 'Services',
    cases: 'Cases',
    about: 'About Us',
    contactUs: 'Contact Us',
    phone: 'Phone',
    email: 'Email',
    address: 'Address',
    addressText: 'Fujian Province, China',
    followUs: 'Follow Us',
    rights: 'All rights reserved',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const value = {
    language: 'en' as const,
    setLanguage: () => {}, // No-op since we're English-only
    t: englishTranslations,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}