import type { TemplateEditorContentProps } from './TemplateEditorContent';

export function buildTemplateEditorContentProps(source: any): TemplateEditorContentProps {
  return {
    activeTemplate: source.activeTemplate,
    activeLoadedVersion: source.activeLoadedVersion,
    resolvedActiveTemplateMeta: source.resolvedActiveTemplateMeta,
    publishStatusMeta: source.publishStatusMeta,
    handleTemplateRestore: source.handleTemplateRestore,
    renderVersionHistoryPanel: source.renderVersionHistoryPanel,
    qr: {
      latestPublishedRecord: source.latestQrPublishedRecord,
      latestDraftRecord: source.latestQrDraftRecord,
      latestVersionRecord: source.latestQrVersionRecord,
      versionNote: source.qrTemplateVersionNote,
      setVersionNote: source.setQrTemplateVersionNote,
      textOverrides: source.qrTemplateTextOverrides,
      updateText: source.updateQrTemplateText,
      data: source.qrTemplateData,
      updateData: source.updateQrTemplateData,
      layout: source.qrTemplateLayout,
      updateLayout: source.updateQrTemplateLayout,
      versionHistory: source.qrVersionHistory,
      restoreAsDraft: (record: any) => source.restoreTemplateVersionAsDraft('qr', record),
    },
    pr: {
      latestPublishedRecord: source.latestPrPublishedRecord,
      latestDraftRecord: source.latestPrDraftRecord,
      latestVersionRecord: source.latestPrVersionRecord,
      versionNote: source.prTemplateVersionNote,
      setVersionNote: source.setPrTemplateVersionNote,
      textOverrides: source.prTemplateTextOverrides,
      updateText: source.updatePrTemplateText,
      data: source.prTemplateData,
      updateData: source.updatePrTemplateData,
      layout: source.prTemplateLayout,
      updateLayout: source.updatePrTemplateLayout,
      versionHistory: source.prVersionHistory,
      restoreAsDraft: (record: any) => source.restoreTemplateVersionAsDraft('pr', record),
    },
    xj: {
      latestPublishedRecord: source.latestXjPublishedRecord,
      latestDraftRecord: source.latestXjDraftRecord,
      latestVersionRecord: source.latestXjVersionRecord,
      versionNote: source.xjTemplateVersionNote,
      setVersionNote: source.setXjTemplateVersionNote,
      layout: source.xjTemplateLayout,
      updateLayout: source.updateXjTemplateLayout,
      data: source.xjTemplateData,
      updateData: source.updateXjTemplateData,
      versionHistory: source.xjVersionHistory,
      updateProductDescription: source.updateXjProductDescription,
      updateProductSpecification: source.updateXjProductSpecification,
      updateProductQuantity: source.updateXjProductQuantity,
      updateProductTargetPrice: source.updateXjProductTargetPrice,
      termPresets: source.XJ_TERMS_PRESETS,
      applyTermsPreset: source.applyXjTermsPresetById,
      clearTerms: source.clearXjTerms,
      restoreDefaultTerms: source.restoreDefaultXjTerms,
      restoreAsDraft: (record: any) => source.restoreTemplateVersionAsDraft('xj', record),
    },
    bj: {
      latestPublishedRecord: source.latestBjPublishedRecord,
      latestDraftRecord: source.latestBjDraftRecord,
      latestVersionRecord: source.latestBjVersionRecord,
      versionNote: source.bjTemplateVersionNote,
      setVersionNote: source.setBjTemplateVersionNote,
      layout: source.bjTemplateLayout,
      updateLayout: source.updateBjTemplateLayout,
      data: source.bjTemplateData,
      updateData: source.updateBjTemplateData,
      versionHistory: source.bjVersionHistory,
      restoreAsDraft: (record: any) => source.restoreTemplateVersionAsDraft('bj', record),
    },
    sc: {
      latestPublishedRecord: source.latestScPublishedRecord,
      latestDraftRecord: source.latestScDraftRecord,
      latestVersionRecord: source.latestScVersionRecord,
      versionNote: source.scTemplateVersionNote,
      setVersionNote: source.setScTemplateVersionNote,
      layout: source.scTemplateLayout,
      updateLayout: source.updateScTemplateLayout,
      data: source.scTemplateData,
      updateData: source.updateScTemplateData,
      versionHistory: source.scVersionHistory,
      productTableColumns: source.scProductTableColumns,
      moveProductTableColumn: source.moveScProductTableColumn,
      updateProductTableColumn: source.updateScProductTableColumn,
      restoreAsDraft: (record: any) => source.restoreTemplateVersionAsDraft('sc', record),
    },
    cg: {
      latestPublishedRecord: source.latestCgPublishedRecord,
      latestDraftRecord: source.latestCgDraftRecord,
      latestVersionRecord: source.latestCgVersionRecord,
      versionNote: source.cgTemplateVersionNote,
      setVersionNote: source.setCgTemplateVersionNote,
      layout: source.cgTemplateLayout,
      updateLayout: source.updateCgTemplateLayout,
      data: source.cgTemplateData,
      updateData: source.updateCgTemplateData,
      versionHistory: source.cgVersionHistory,
      productTableColumns: source.cgProductTableColumns,
      moveProductTableColumn: source.moveCgProductTableColumn,
      updateProductTableColumn: source.updateCgProductTableColumn,
      restoreAsDraft: (record: any) => source.restoreTemplateVersionAsDraft('cg', record),
    },
    pi: {
      latestPublishedRecord: source.latestPiPublishedRecord,
      latestDraftRecord: source.latestPiDraftRecord,
      latestVersionRecord: source.latestPiVersionRecord,
      versionNote: source.piTemplateVersionNote,
      setVersionNote: source.setPiTemplateVersionNote,
      layout: source.piTemplateLayout,
      updateLayout: source.updatePiTemplateLayout,
      data: source.piTemplateData,
      updateData: source.updatePiTemplateData,
      versionHistory: source.piVersionHistory,
      goodsTableColumns: source.piGoodsTableColumns,
      moveGoodsTableColumn: source.movePiGoodsTableColumn,
      updateGoodsTableColumn: source.updatePiGoodsTableColumn,
      restoreAsDraft: (record: any) => source.restoreTemplateVersionAsDraft('pi', record),
    },
    ci: {
      latestPublishedRecord: source.latestCiPublishedRecord,
      latestDraftRecord: source.latestCiDraftRecord,
      latestVersionRecord: source.latestCiVersionRecord,
      versionNote: source.ciTemplateVersionNote,
      setVersionNote: source.setCiTemplateVersionNote,
      layout: source.ciTemplateLayout,
      updateLayout: source.updateCiTemplateLayout,
      data: source.ciTemplateData,
      updateData: source.updateCiTemplateData,
      versionHistory: source.ciVersionHistory,
      goodsTableColumns: source.ciGoodsTableColumns,
      moveGoodsTableColumn: source.moveCiGoodsTableColumn,
      updateGoodsTableColumn: source.updateCiGoodsTableColumn,
      restoreAsDraft: (record: any) => source.restoreTemplateVersionAsDraft('ci', record),
    },
    pl: {
      latestPublishedRecord: source.latestPlPublishedRecord,
      latestDraftRecord: source.latestPlDraftRecord,
      latestVersionRecord: source.latestPlVersionRecord,
      versionNote: source.plTemplateVersionNote,
      setVersionNote: source.setPlTemplateVersionNote,
      layout: source.plTemplateLayout,
      updateLayout: source.updatePlTemplateLayout,
      data: source.plTemplateData,
      updateData: source.updatePlTemplateData,
      versionHistory: source.plVersionHistory,
      restoreAsDraft: (record: any) => source.restoreTemplateVersionAsDraft('pl', record),
    },
    soa: {
      latestPublishedRecord: source.latestSoaPublishedRecord,
      latestDraftRecord: source.latestSoaDraftRecord,
      latestVersionRecord: source.latestSoaVersionRecord,
      versionNote: source.soaTemplateVersionNote,
      setVersionNote: source.setSoaTemplateVersionNote,
      layout: source.soaTemplateLayout,
      updateLayout: source.updateSoaTemplateLayout,
      data: source.soaTemplateData,
      updateData: source.updateSoaTemplateData,
      versionHistory: source.soaVersionHistory,
      restoreAsDraft: (record: any) => source.restoreTemplateVersionAsDraft('soa', record),
    },
    ing: {
      latestPublishedRecord: source.latestInquiryPublishedRecord,
      latestDraftRecord: source.latestInquiryDraftRecord,
      latestVersionRecord: source.latestInquiryVersionRecord,
      versionNote: source.inquiryTemplateVersionNote,
      setVersionNote: source.setInquiryTemplateVersionNote,
      layout: source.inquiryTemplateLayout,
      updateLayout: source.updateInquiryTemplateLayout,
      data: source.inquiryTemplateData,
      updateData: source.updateInquiryTemplateData,
      versionHistory: source.inquiryVersionHistory,
      productTableColumns: source.inquiryProductTableColumns,
      moveProductTableColumn: source.moveInquiryProductTableColumn,
      updateProductTableColumn: source.updateInquiryProductTableColumn,
      publishValidation: source.inquiryPublishValidation,
      requirementFields: source.CUSTOMER_INQUIRY_REQUIREMENT_FIELDS,
      activeRequirementField: source.activeInquiryRequirementField,
      setActiveRequirementField: source.setActiveInquiryRequirementField,
      restoreAsDraft: (record: any) => source.restoreTemplateVersionAsDraft('ing', record),
    },
    qt: {
      latestPublishedRecord: source.latestQuotationPublishedRecord,
      latestDraftRecord: source.latestQuotationDraftRecord,
      latestVersionRecord: source.latestQuotationVersionRecord,
      versionNote: source.quotationTemplateVersionNote,
      setVersionNote: source.setQuotationTemplateVersionNote,
      layout: source.quotationTemplateLayout,
      updateLayout: source.updateQuotationTemplateLayout,
      data: source.quotationTemplateData,
      updateData: source.updateQuotationTemplateData,
      versionHistory: source.quotationVersionHistory,
      updateProductName: source.updateQuotationProductName,
      updateQuantity: source.updateQuotationProductQuantity,
      updateUnitPrice: source.updateQuotationProductUnitPrice,
      productTableColumns: source.quotationProductTableColumns,
      moveProductTableColumn: source.moveQuotationProductTableColumn,
      updateProductTableColumn: source.updateQuotationProductTableColumn,
      restoreAsDraft: (record: any) => source.restoreTemplateVersionAsDraft('qt', record),
    },
  };
}
