import type { DocumentConditionGroup } from '../../../types/documentConditions';
import { translateTradingRequirementValue } from '../../../utils/procurementRequestContext';
import {
  type QuoteRequirementDocumentData,
  buildDefaultQuoteRequirementTextOverrides,
} from '../../documents/templates/QuoteRequirementDocument';
import { type XJData } from '../../documents/templates/XJDocument';
import {
  DEFAULT_SALES_CONTRACT_PRODUCT_TABLE_COLUMNS,
  type SalesContractData,
} from '../../documents/templates/SalesContractDocument';
import {
  DEFAULT_PURCHASE_ORDER_PRODUCT_TABLE_COLUMNS,
  type PurchaseOrderData,
} from '../../documents/templates/PurchaseOrderDocument';
import {
  DEFAULT_PROFORMA_INVOICE_GOODS_TABLE_COLUMNS,
  type ProformaInvoiceData,
} from '../../documents/templates/ProformaInvoiceDocument';
import {
  DEFAULT_COMMERCIAL_INVOICE_GOODS_TABLE_COLUMNS,
  type CommercialInvoiceData,
} from '../../documents/templates/CommercialInvoiceDocument';
import { type PackingListData } from '../../documents/templates/PackingListDocument';
import { type StatementOfAccountData } from '../../documents/templates/StatementOfAccountDocument';
import {
  DEFAULT_CUSTOMER_INQUIRY_TYPOGRAPHY,
  DEFAULT_CUSTOMER_INQUIRY_PRODUCT_TABLE_COLUMNS,
  type CustomerInquiryData,
} from '../../documents/templates/CustomerInquiryDocument';
import {
  DEFAULT_QUOTATION_PRODUCT_TABLE_COLUMNS,
  type QuotationData,
} from '../../documents/templates/QuotationDocument';
import { type SupplierQuotationData } from '../../documents/templates/SupplierQuotationDocument';
import { buildPaymentTermsText } from '../../../lib/paymentFlow';

// 模板中心 seed 不是演示数据，而是当前确认无误的基线模板。
// 规则：
// 1. 仅在模板首次创建、或远端版本数据完全为空时作为初始化兜底使用。
// 2. 一旦 Supabase 中已有真实版本，工作台必须优先使用版本数据，不能再被 seed 反向覆盖。
// 3. 以后模板基线升级时，统一更新这组 seed 与 baseline 标记。
export const TEMPLATE_CENTER_SEED_BASELINE = {
  label: 'template-center-baseline',
  confirmedAt: '2026-03-25',
  description: 'Current confirmed workspace seed baseline for template center',
} as const;

export const BASELINE_QR_CONDITION_GROUPS: DocumentConditionGroup[] = [
  {
    key: 'business-instructions',
    title: '业务部说明',
    titleEn: 'SALES DEPT INSTRUCTIONS',
    items: [
      { key: 'packaging', label: '1. 客户包装要求', value: '外箱需要英文唛头，零售包装需挂卡设计，适合北美商超陈列。' },
      { key: 'payment', label: '2. 付款方式', value: '请优先争取 T/T 30% 预付款 + 70% 出货前付清。' },
      { key: 'quality', label: '3. 质量要求', value: '必须满足 UL / FCC / RoHS，重点确认批量稳定性。' },
      { key: 'delivery', label: '4. 交期要求', value: '首批交付目标 30 天内，超过 35 天需单独说明原因。' },
    ],
  },
];

export const BASELINE_QR_TEMPLATE_SEED: QuoteRequirementDocumentData = {
  requirementNo: 'QR-NA-260304-0001',
  requirementDate: '2026-03-04',
  sourceInquiryNo: 'ING-NA-260303-0012',
  requiredResponseDate: '2026-03-08',
  requiredDeliveryDate: '2026-04-10',
  customer: {
    companyName: 'ABC Trading Corporation',
    contactPerson: 'John Smith',
    email: 'john.smith@abctrading.com',
    phone: '+1-323-555-0123',
    address: '123 Main Street, Suite 500, Los Angeles, CA 90001, USA',
    region: 'North America',
    businessType: '建材分销',
  },
  products: [
    {
      no: 1,
      modelNo: 'GFCI-001',
      productName: 'GFCI Outlet',
      specification: '20A, 125V, Tamper-Resistant, Weather-Resistant, UL Listed',
      quantity: 5000,
      unit: 'PCS',
      unitPrice: 2.5,
      totalPrice: 12500,
      remarks: '白色，带LED指示灯',
    },
    {
      no: 2,
      modelNo: 'WRC-001',
      productName: 'Weather-Resistant Cover',
      specification: 'IP66 rated, single gang, clear polycarbonate',
      quantity: 2000,
      unit: 'PCS',
      unitPrice: 1.45,
      totalPrice: 2900,
      remarks: '适配北美户外插座',
    },
  ],
  customerRequirements: {
    deliveryTerms: 'FOB Xiamen / CIF Los Angeles',
    paymentTerms: 'T/T or L/C at sight',
    qualityStandard: 'UL, FCC, CE, RoHS',
    packaging: '出口纸箱 + 木托盘，适合海运',
    specialRequirements: '需要英文说明书与安装指南，并确认零售包装结构。',
  },
  conditionGroups: BASELINE_QR_CONDITION_GROUPS,
  salesDeptNotes: [
    '1. Price Terms / 价格条款',
    'Original: FOB Xiamen / CIF Los Angeles',
    '中文: FOB 厦门 / CIF 洛杉矶',
    '',
    '2. Delivery Time / 交期要求',
    'Original: Within 30 days after order confirmation',
    '中文: 订单确认后30天内',
    '',
    '3. Payment Terms / 付款条款',
    'Original: T/T or L/C at sight',
    '中文: T/T 或即期信用证',
  ].join('\n'),
  purchaseDeptFeedback: '此区域为流程节点实际反馈区域，模板中心仅用于定义结构与初始占位文案。',
  urgency: 'high',
  createdBy: '模板管理员',
};

export const BASELINE_PR_CONDITION_GROUPS: DocumentConditionGroup[] = [
  {
    key: 'procurement-allocation',
    title: '采购分配原则',
    titleEn: 'PROCUREMENT ALLOCATION RULES',
    items: [
      { key: 'split', label: '1. 拆分原则', value: '按产品线、供应商专长、交期风险和起订量综合拆分，不要求单一供应商全包。' },
      { key: 'supplier', label: '2. 供应商策略', value: '同一客户订单可对应多个供应商，优先保障交期、质量稳定性与历史履约表现。' },
      { key: 'contract', label: '3. 合同输出', value: 'PR 完成分配后，应按供应商生成对应采购合同 CG，每个供应商一份。' },
      { key: 'privacy', label: '4. 脱敏要求', value: 'PR 仅暴露采购分配所需的订单摘要与脱敏客户信息，不展示终端客户敏感资料。' },
    ],
  },
];

export const BASELINE_PR_TEMPLATE_SEED: QuoteRequirementDocumentData = {
  requirementNo: 'PR-NA-260325-0001',
  requirementDate: '2026-03-25',
  sourceInquiryNo: 'SC-NA-260320-0008',
  requiredResponseDate: '2026-03-27',
  requiredDeliveryDate: '2026-04-18',
  customer: {
    companyName: 'North America Key Account A',
    contactPerson: 'Account Owner',
    email: 'sales.masked@cosun.example',
    phone: '+1-000-***-****',
    address: 'Destination market: Los Angeles, CA / Customer detail masked',
    region: 'North America',
    businessType: '建材渠道客户（脱敏）',
  },
  products: [
    {
      no: 1,
      modelNo: 'SC-LINE-001',
      productName: 'GFCI Outlet Main Housing',
      specification: '客户订单主产品，建议分配给 Supplier A，承担 3,000 PCS',
      quantity: 3000,
      unit: 'PCS',
      unitPrice: 0,
      totalPrice: 0,
      remarks: '拟分配供应商：Supplier A / 目标CG：CG-A',
    },
    {
      no: 2,
      modelNo: 'SC-LINE-002',
      productName: 'Weather-Resistant Cover',
      specification: '配件产品，建议分配给 Supplier B，承担 2,000 PCS',
      quantity: 2000,
      unit: 'PCS',
      unitPrice: 0,
      totalPrice: 0,
      remarks: '拟分配供应商：Supplier B / 目标CG：CG-B',
    },
  ],
  customerRequirements: {
    deliveryTerms: '分配完成后按供应商分别生成 CG，并同步交期承诺',
    paymentTerms: '沿用 SC 已确认付款框架，采购侧按供应商单独执行',
    qualityStandard: '不得降低 SC 约定质量标准，分供应商执行统一验收口径',
    packaging: '按客户订单要求执行，PR 中仅保留分配与协同所需摘要',
    specialRequirements: '允许一单多供应商，必须标明每个供应商负责的产品、数量和目标交付节点。',
  },
  conditionGroups: BASELINE_PR_CONDITION_GROUPS,
  salesDeptNotes: [
    '1. Procurement Allocation Goal / 采购分配目标',
    '将销售合同中的产品拆分给最合适的供应商，并形成后续采购合同。',
    '',
    '2. Supplier Split Logic / 供应商拆分逻辑',
    '同一订单允许拆分给多个供应商，按产品专长、MOQ、交期和历史履约表现综合判断。',
    '',
    '3. CG Output Rule / 采购合同输出规则',
    '每个被选定供应商最终生成一份对应的采购合同 CG。',
  ].join('\n'),
  purchaseDeptFeedback: '此区域用于回写采购分配结果，如：已分配 2 家供应商，待生成 2 份 CG。',
  urgency: 'high',
  createdBy: '采购管理员',
};

export const BASELINE_XJ_TEMPLATE_SEED: XJData = {
  xjNo: 'XJ-251218-1001',
  xjDate: '2025-12-18',
  requiredResponseDate: '2025-12-25',
  requiredDeliveryDate: '2026-01-15',
  inquiryDescription: '围绕五金配件系列产品进行首轮正式询价，请提供完整报价和交期说明。',
  buyer: {
    name: '',
    nameEn: '',
    address: '',
    addressEn: '',
    tel: '',
    email: '',
    contactPerson: '',
  },
  supplier: {
    companyName: '深圳市优质五金制品有限公司',
    address: '广东省深圳市宝安区西乡工业园',
    contactPerson: '李经理',
    tel: '+86-755-2888-8888',
    email: 'sales@supplier.com',
    supplierCode: 'SUP-ELEC-001',
  },
  products: [
    {
      no: 1,
      modelNo: 'WJ-2024-001',
      description: '不锈钢门锁',
      specification: '304不锈钢材质，带钥匙3把，表面拉丝处理',
      quantity: 1000,
      unit: '套',
      targetPrice: 'USD 12.50',
      remarks: '需配备安装说明书',
    },
    {
      no: 2,
      modelNo: 'WJ-2024-002',
      description: '铝合金门把手',
      specification: '6063铝合金，长度150mm，银色阳极氧化',
      quantity: 2000,
      unit: '个',
      targetPrice: 'USD 3.80',
    },
    {
      no: 3,
      modelNo: 'WJ-2024-003',
      description: '铜合金铰链',
      specification: '4寸静音铰链，承重80kg，镀铬处理',
      quantity: 3000,
      unit: '个',
      targetPrice: 'USD 2.20',
    },
  ],
  terms: {
    currency: 'USD',
    paymentTerms: buildPaymentTermsText('tt_deposit_balance_before_shipment', 'before_shipment'),
    deliveryTerms: 'EXW 工厂交货',
    deliveryAddress: '福建省福州市仓山区金山工业区',
    qualityStandard: '产品需符合国家GB/T 27922-2011标准，并优先提供 ISO 9001 / CE 等认证材料。',
    inspectionMethod: '到货后进行外观和功能检测，抽检率5%，不合格品按比例扣款或退换货处理。',
    deliveryRequirement: '要求交货日期：2026-01-15，如无法按期交货需提前7天告知并说明原因。',
    packaging: '标准出口包装，内层气泡膜，外层纸箱+木托盘，需防潮防震。',
    shippingMarks: '中性唛头，不显示最终客户信息。',
    inspectionRequirement: '出货前需提供产品照片和装箱照片，必要时安排第三方检验。',
    technicalDocuments: '需提供产品说明书（中英文）、材质检测报告、RoHS检测报告。',
    ipRights: '供应商确认所供产品不侵犯任何第三方知识产权。',
    confidentiality: '双方对价格信息、技术资料、客户信息承担保密义务。',
    sampleRequirement: '首次合作需提供2-3个样品供质量确认。',
    moq: '请在报价中注明最小起订量（MOQ）要求。',
    remarks: '报价有效期请不少于30天，交货周期请明确标注。',
  },
};

export const BASELINE_BJ_TEMPLATE_SEED: SupplierQuotationData = {
  quotationNo: 'BJ-NA-260304-0001',
  quotationDate: '2026-03-04',
  validUntil: '2026-04-03',
  xjReference: 'XJ-NA-260304-0001',
  supplier: {
    companyName: '深圳市优质五金制品有限公司',
    companyNameEn: 'Shenzhen Quality Metal Products Co., Ltd.',
    address: '广东省深圳市宝安区西乡工业园88号',
    addressEn: 'No.88 Xixiang Industrial Park, Baoan District, Shenzhen, Guangdong, China',
    tel: '+86-755-2888-8888',
    email: 'sales@supplier.com',
    contactPerson: '李经理',
    supplierCode: 'SUP-ELEC-001',
    logo: '',
  },
  buyer: {
    name: '',
    nameEn: '',
    address: '',
    addressEn: '',
    tel: '',
    email: '',
    contactPerson: '',
  },
  products: [
    {
      no: 1,
      modelNo: 'GFCI-001',
      description: 'GFCI Outlet',
      specification: '20A, 125V, Tamper-Resistant, Weather-Resistant, UL Listed',
      quantity: 5000,
      unit: 'PCS',
      unitPrice: 2.5,
      currency: 'USD',
      remarks: '白色，带 LED 指示灯',
    },
    {
      no: 2,
      modelNo: 'WRC-001',
      description: 'Weather-Resistant Cover',
      specification: 'IP66 rated, single gang, clear polycarbonate',
      quantity: 2000,
      unit: 'PCS',
      unitPrice: 1.45,
      currency: 'USD',
      remarks: '适配北美户外插座',
    },
  ],
  terms: {
    paymentTerms: buildPaymentTermsText('tt_deposit_balance_before_shipment', 'before_shipment'),
    deliveryTerms: 'EXW 深圳工厂',
    deliveryTime: '收到预付款后 15-20 天',
    deliveryAddress: '福建省福州市仓山区金山工业区',
    moq: 'GFCI Outlet：1000 PCS；Weather-Resistant Cover：1000 PCS',
    qualityStandard: '符合 UL / FCC / CE / RoHS 标准',
    warranty: '12个月质保，自交货日期起计算',
    packaging: '标准出口包装，内层气泡膜，外层纸箱+木托盘',
    shippingMarks: '中性唛头或按客户要求定制',
    remarks: '报价有效期30天，大批量订单可协商价格。',
  },
  supplierRemarks: {
    content: '本报价基于当前原材料行情制定，如材料价格波动超过10%，我司保留价格调整权利。',
    remarkDate: '2026-03-04',
    remarkBy: '李经理',
  },
};

export const BASELINE_SC_TEMPLATE_SEED: SalesContractData = {
  contractNo: 'SC-NA-20251220-001',
  contractDate: '2025-12-20',
  quotationNo: 'QT-NA-20251210-001',
  region: 'NA',
  seller: {
    name: '',
    nameEn: '',
    address: '',
    addressEn: '',
    tel: '',
    fax: '',
    email: '',
    legalRepresentative: '',
    businessLicense: '',
  },
  buyer: {
    companyName: 'ABC Trading Corporation',
    contactPerson: 'John Smith',
    address: '123 Main Street, Suite 500, Los Angeles, CA 90001, USA',
    country: 'United States',
    email: 'john.smith@abctrading.com',
    tel: '+1-323-555-0123',
  },
  products: [
    {
      no: 1,
      description: 'GFCI Outlet - 20A, 125V, Tamper-Resistant, Weather-Resistant, UL Listed, White with LED',
      specification: '20A, 125V, Tamper-Resistant, Weather-Resistant, UL Listed, White with LED',
      hsCode: '8536.6990',
      quantity: 5000,
      unit: 'pcs',
      unitPrice: 2.85,
      currency: 'USD',
      amount: 14250,
      deliveryTime: '25-30 days',
    },
    {
      no: 2,
      description: 'Weather-Resistant Cover - IP66, Single Gang, Clear Polycarbonate',
      specification: 'IP66, Single Gang, Clear Polycarbonate',
      hsCode: '3926.9090',
      quantity: 2000,
      unit: 'pcs',
      unitPrice: 1.65,
      currency: 'USD',
      amount: 3300,
      deliveryTime: '20-25 days',
    },
    {
      no: 3,
      description: 'Decora Wall Plate - Screwless Design, UV Resistant, Multi-color',
      specification: 'Screwless Design, UV Resistant, Multi-color',
      hsCode: '3926.9090',
      quantity: 3000,
      unit: 'pcs',
      unitPrice: 0.95,
      currency: 'USD',
      amount: 2850,
      deliveryTime: '20-25 days',
    },
    {
      no: 4,
      description: 'USB Wall Outlet - Dual USB Ports, 4.2A Total Output, Smart Charging Technology',
      specification: 'Dual USB-A ports, 4.2A combined, tamper-resistant receptacles, UL certified',
      hsCode: '8536.6990',
      quantity: 3500,
      unit: 'pcs',
      unitPrice: 3.95,
      currency: 'USD',
      amount: 13825,
      deliveryTime: '30-35 days',
    },
  ],
  terms: {
    totalAmount: 34225,
    currency: 'USD',
    tradeTerms: 'FOB Xiamen, China',
    paymentTerms: buildPaymentTermsText('tt_deposit_balance_before_shipment', 'before_shipment'),
    depositAmount: 10267.5,
    balanceAmount: 23957.5,
    deliveryTime: '35-45 days after receiving deposit',
    portOfLoading: 'Xiamen Port, China',
    portOfDestination: 'Los Angeles Port, USA',
    packing: 'Export standard carton with wooden pallets, shrink-wrapped, suitable for ocean freight',
    inspection: 'Buyer inspection or third-party inspection before shipment.',
    warranty: '12 months warranty for manufacturing defects from delivery date.',
  },
  liabilityTerms: {
    sellerDefault: 'If seller fails to deliver on time without valid reason or force majeure, buyer may request deposit refund and compensation.',
    buyerDefault: 'If buyer fails to pay within agreed time, seller may suspend shipment and claim related losses.',
    forceMajeure: 'Both parties are exempted from liabilities arising from force majeure events beyond reasonable control.',
  },
  disputeResolution: {
    governingLaw: 'Laws of the People’s Republic of China.',
    arbitration: 'Disputes shall be settled by friendly negotiation, failing which CIETAC Xiamen shall arbitrate.',
  },
  signature: {
    sellerSignatory: 'Wang Ming (Legal Representative)',
    buyerSignatory: 'John Smith (Purchasing Manager)',
    signDate: '2025-12-20',
  },
  templateSettings: {
    productTableColumns: DEFAULT_SALES_CONTRACT_PRODUCT_TABLE_COLUMNS,
  },
};

export const BASELINE_CG_TEMPLATE_SEED: PurchaseOrderData = {
  poNo: 'CG-20251220-001',
  poDate: '2025-12-20',
  requiredDeliveryDate: '2026-01-25',
  buyer: {
    name: '',
    nameEn: '',
    address: '',
    addressEn: '',
    tel: '',
    email: '',
    contactPerson: '',
  },
  supplier: {
    companyName: 'Shenzhen Electronics Manufacturing Co., Ltd.',
    address: 'No.88 Industrial Road, Baoan District, Shenzhen, Guangdong, China',
    contactPerson: 'Chen Wei',
    tel: '+86-755-8888-9999',
    email: 'sales@szelec.com',
    supplierCode: 'SUP-GD-001',
    bankInfo: {
      bankName: '中国工商银行深圳宝安支行',
      accountName: 'Shenzhen Electronics Manufacturing Co., Ltd.',
      accountNumber: '4000 0212 0920 1234 567',
      swiftCode: 'ICBKCNBJSZN',
      bankAddress: 'No.123 Baoan Avenue, Baoan District, Shenzhen, Guangdong, China',
      currency: 'CNY/USD',
    },
  },
  products: [
    {
      no: 1,
      itemCode: 'ITEM-GFCI-001',
      description: 'GFCI Outlet Components - Main Housing',
      specification: '20A, 125V rated, Fire-resistant PC plastic, UL94 V-0',
      quantity: 5000,
      unit: 'pcs',
      unitPrice: 1.85,
      currency: 'CNY',
      amount: 9250,
      deliveryDate: '2026-01-20',
      remarks: 'White color, with mounting holes',
    },
    {
      no: 2,
      itemCode: 'ITEM-GFCI-002',
      description: 'GFCI Circuit Board Assembly',
      specification: 'PCB with IC chip, LED indicator, certified components',
      quantity: 5000,
      unit: 'pcs',
      unitPrice: 0.95,
      currency: 'CNY',
      amount: 4750,
      deliveryDate: '2026-01-20',
    },
    {
      no: 3,
      itemCode: 'ITEM-WRC-001',
      description: 'Weather-Resistant Cover Raw Material',
      specification: 'Clear Polycarbonate sheets, IP66 grade, UV stabilized',
      quantity: 100,
      unit: 'kg',
      unitPrice: 8.5,
      currency: 'CNY',
      amount: 850,
      deliveryDate: '2026-01-15',
    },
  ],
  terms: {
    totalAmount: 14850,
    currency: 'CNY',
    paymentTerms: '30 days after delivery and inspection',
    deliveryTerms: 'EXW Shenzhen Factory',
    deliveryAddress: '',
    qualityStandard: 'Meet UL, CE, RoHS standards. Samples must be approved before bulk production.',
    inspectionMethod: 'Third-party inspection (SGS or equivalent) or buyer inspection at supplier factory',
    packaging: '采用出口标准纸箱包装，每箱需标注采购单号、物料编码、数量、毛重净重。外包装需防潮、防震处理。',
    shippingMarks: '唛头需注明"COSUN"字样、合同编号CG-20251220-001、目的地厦门，并标注"小心轻放"、"防潮"标识。',
    deliveryPenalty: '供应商未能按约定时间交货的，每延误一天，应按延误交货部分货款的0.5%支付违约金，但违约金总额不超过延误交货部分货款的5%。',
    qualityPenalty: '产品质量不符合约定标准的，采购方有权拒收。如已收货发现质量问题，供应商应在7个工作日内无条件退换货，并承担由此产生的一切费用及损失。',
    warrantyPeriod: '12个月（自交货验收合格之日起计算）',
    warrantyTerms: '质保期内因产品质量问题造成的损失，供应商应负责免费维修或更换，并承担相关运费。',
    returnPolicy: '到货后7个工作日内完成验收，验收不合格的产品采购方有权退货。',
    confidentiality: '双方对本合同内容及合作过程中知悉的商业秘密承担保密义务。',
    ipRights: '供应商保证所供产品不侵犯任何第三方知识产权。',
    forceMajeure: '因不可抗力导致合同无法履行的，双方可协商延期履行或解除合同。',
    disputeResolution: '协商不成的，任何一方均可向采购方所在地人民法院提起诉讼。',
    applicableLaw: '中华人民共和国法律（不含冲突法规则）',
    contractValidity: '本采购合同自双方签章之日起生效，至所有产品交付验收合格且付款完成后自动终止。',
    modification: '任何修改或补充必须经双方书面同意并签署补充协议。',
    termination: '如一方严重违约且在收到书面通知后15日内仍未纠正，守约方有权解除合同。',
  },
  templateSettings: {
    productTableColumns: DEFAULT_PURCHASE_ORDER_PRODUCT_TABLE_COLUMNS,
  },
};

export const XJ_TERMS_PRESETS: XjTermsPreset[] = [
  {
    id: 'electronics-standard',
    name: '电子品常用模板',
    description: '适合插座、开关、五金电工类采购询价',
    terms: {
      currency: 'USD',
      paymentTerms: buildPaymentTermsText('tt_deposit_balance_before_shipment', 'before_shipment'),
      deliveryTerms: 'EXW 工厂交货',
      deliveryAddress: '福建省福州市仓山区金山工业区',
      deliveryRequirement: '要求交货日期需明确标注，如无法按期交货需提前7天书面通知。',
      qualityStandard: '产品需符合国家标准及出口市场认证要求，并优先提供 ISO 9001 / CE / RoHS 等资料。',
      inspectionMethod: '到货后进行外观和功能抽检，不合格品按比例扣款或退换货处理。',
      packaging: '标准出口包装，内层气泡膜，外层纸箱+木托盘，需防潮防震。',
      shippingMarks: '中性唛头，不显示最终客户信息。',
      inspectionRequirement: '出货前需提供产品照片和装箱照片，必要时安排第三方检验。',
      technicalDocuments: '需提供产品说明书、材质检测报告、RoHS 检测报告及相关认证副本。',
      ipRights: '供应商确认所供产品不侵犯任何第三方知识产权。',
      confidentiality: '双方对价格信息、技术资料、客户信息承担保密义务。',
      sampleRequirement: '首次合作需提供 2-3 个样品供质量确认。',
      moq: '请在报价中注明最小起订量（MOQ）要求。',
      remarks: '报价有效期请不少于30天，交货周期请明确标注。',
    },
  },
  {
    id: 'export-general',
    name: '出口通用模板',
    description: '适合大部分标准出口采购场景',
    terms: {
      currency: 'USD',
      paymentTerms: buildPaymentTermsText('tt_deposit_balance_against_bl', 'after_shipment'),
      deliveryTerms: 'FOB 中国港口',
      deliveryRequirement: '供应商需按确认交期出货，延误须提前说明原因并给出补救计划。',
      packaging: '出口标准包装，满足海运或陆运要求，外箱需贴产品标签。',
      shippingMarks: '按我司提供唛头执行，如无特别要求使用中性唛头。',
      inspectionRequirement: '大货出货前需提供照片、视频，必要时配合验货。',
      technicalDocuments: '需提供装箱资料、产品规格书、测试报告及认证文件。',
      confidentiality: '报价、图纸、客户资料不得向第三方泄露。',
      remarks: '请明确报价有效期、产能、打样周期及量产周期。',
    },
  },
  {
    id: 'strict-quality',
    name: '严格质检模板',
    description: '适合高质量要求、需强化验货与文件的采购',
    terms: {
      paymentTerms: 'T/T 30% 预付，70% 验货通过后付清。',
      qualityStandard: '产品必须满足指定技术规格及样品标准，批次一致性需受控。',
      inspectionMethod: '执行 AQL 抽检标准，外观、尺寸、功能均需检验，检验不合格批次不得出货。',
      inspectionRequirement: '出货前需安排第三方验货，并提交完整验货报告。',
      technicalDocuments: '需提供检验报告、原材料证明、认证文件、关键工序控制说明。',
      sampleRequirement: '量产前须确认封样，后续交货必须与封样一致。',
      remarks: '如发生质量异常，供应商需在48小时内回复纠正预防措施。',
    },
  },
];

export const EMPTY_XJ_TERMS: XJData['terms'] = {
  currency: '',
  paymentTerms: '',
  deliveryTerms: '',
  deliveryAddress: '',
  deliveryRequirement: '',
  qualityStandard: '',
  inspectionMethod: '',
  packaging: '',
  shippingMarks: '',
  inspectionRequirement: '',
  technicalDocuments: '',
  ipRights: '',
  confidentiality: '',
  sampleRequirement: '',
  moq: '',
  remarks: '',
};

export const BASELINE_PI_TEMPLATE_SEED: ProformaInvoiceData = {
  invoiceNo: 'B125051209',
  costNo: 'KH13100001',
  scNo: '',
  invoiceDate: 'May 12, 2025',
  seller: {
    name: '',
    nameEn: '',
    unit: 'Unit1807',
    building: 'C1# Building',
    zone: 'Zone C',
    plaza: 'Wanda Plaza',
    district: 'Cangshan Dist',
    city: 'Fuzhou',
    province: 'Fujian',
    country: 'China',
    cell: '',
    email: '',
  },
  buyer: {
    companyName: 'Aluminium & Light Industries Co. (ALICO) Ltd',
    poBox: 'Box 6011 Sharjah UAE',
    contactPerson: 'Mohan MV +971655824441(90)',
  },
  products: [
    {
      seqNo: 1,
      itemNo: '1605909',
      description: '5101# Block Materials- ABS',
      specification: 'Color: in white',
      quantity: 10000,
      unit: 'pc',
      unitPrice: 0.245,
      currency: 'US$',
      extendedValue: 2450,
    },
  ],
  freight: {
    type: 'Air Freight',
    terms: 'collected by the buyer',
  },
  totalValue: 2450,
  totalCurrency: 'US$',
  priceTerms: 'EX.W (XIAMEN)',
  bankInfo: {
    beneficiary: '',
    beneficiaryAddress: '',
    accountNo: '',
    bank: '',
    bankAddress: '',
    swiftCode: '',
  },
  remarks: {
    priceTerms: 'Price Term: EX WARE OF XIAMEN',
    containerType: 'Container Type: 1 x in bulk',
    paymentTerms: 'Term of payment: 100% prepayment before preparation of samples and mass production',
    portOfLoading: 'Port of Loading: XIAMEN',
    shipmentDate: 'Date of Shipment: MAY 5, 2025',
    others: [
      '',
      '1. Delivery date:',
      '   Samples: none',
      '   Mass production: 15 days on confirming the samples.',
      '2. Approved drawing of the Art #5101 confirmed by "mohan.mv@alicolite.net" on 3 April 2016',
      '3. Extra fee $100 / charge ≈ 10000pcs/order',
    ],
  },
  footer: {
    tagline: 'One-stop Project Sourcing Solution Provider',
    currentPage: 1,
    totalPages: 2,
  },
  templateSettings: {
    goodsTableColumns: DEFAULT_PROFORMA_INVOICE_GOODS_TABLE_COLUMNS,
  },
};

export const BASELINE_CI_TEMPLATE_SEED: CommercialInvoiceData = {
  invoiceNo: 'CI-20260215-001',
  invoiceDate: '2026-02-15',
  contractNo: 'SC-NA-20251220-001',
  exporter: {
    name: '',
    nameEn: '',
    address: '',
    addressEn: '',
    tel: '',
  },
  importer: {
    name: 'ABC TRADING CORPORATION',
    address: '123 Main Street, Suite 500, Los Angeles, CA 90001',
    country: 'United States of America',
    tel: '+1-323-555-0123',
  },
  shippingMarks: {
    mainMark: 'ABC-LA-001',
    sideMark: 'C/NO. 1-50',
    cautionMark: 'MADE IN CHINA\nFRAGILE - HANDLE WITH CARE',
  },
  goods: [
    {
      no: 1,
      description: 'GFCI Outlet, 20A 125V, Tamper-Resistant, Weather-Resistant, UL Listed',
      hsCode: '8536.6990',
      quantity: 5000,
      unit: 'PCS',
      unitPrice: 2.85,
      currency: 'USD',
      amount: 14250,
      grossWeight: 0.25,
      netWeight: 0.22,
    },
    {
      no: 2,
      description: 'Weather-Resistant Cover, IP66, Single Gang, Clear Polycarbonate',
      hsCode: '3926.9090',
      quantity: 2000,
      unit: 'PCS',
      unitPrice: 1.65,
      currency: 'USD',
      amount: 3300,
      grossWeight: 0.15,
      netWeight: 0.12,
    },
  ],
  shipping: {
    tradeTerms: 'FOB XIAMEN',
    paymentTerms: 'T/T',
    portOfLoading: 'Xiamen Port, China',
    portOfDischarge: 'Los Angeles Port, USA',
    finalDestination: 'Los Angeles, California, USA',
    vesselName: 'COSCO PACIFIC',
    blNo: 'COSU1234567890',
  },
  packing: {
    totalCartons: 50,
    totalGrossWeight: 1550,
    totalNetWeight: 1350,
    totalMeasurement: 3.75,
  },
  templateSettings: {
    goodsTableColumns: DEFAULT_COMMERCIAL_INVOICE_GOODS_TABLE_COLUMNS,
  },
};

export const BASELINE_PL_TEMPLATE_SEED: PackingListData = {
  plNo: 'PL-20260215-001',
  invoiceNo: 'CI-20260215-001',
  date: '2026-02-15',
  exporter: {
    name: '',
    address: '',
  },
  importer: {
    name: 'ABC TRADING CORPORATION',
    address: '123 Main Street, Suite 500, Los Angeles, CA 90001, USA',
  },
  shippingMarks: 'ABC-LA-001\nC/NO. 1-50\nMADE IN CHINA\nFRAGILE - HANDLE WITH CARE',
  packages: [
    {
      cartonNo: '1-25',
      description: 'GFCI Outlet, 20A 125V, TR/WR, UL Listed',
      qtyPerCarton: 200,
      totalCartons: 25,
      totalQty: 5000,
      unit: 'PCS',
      netWeight: 22,
      grossWeight: 25,
      measurement: 0.06,
      totalNW: 550,
      totalGW: 625,
      totalCBM: 1.5,
    },
    {
      cartonNo: '26-50',
      description: 'Weather-Resistant Cover, IP66, Clear PC',
      qtyPerCarton: 80,
      totalCartons: 25,
      totalQty: 2000,
      unit: 'PCS',
      netWeight: 12,
      grossWeight: 14,
      measurement: 0.05,
      totalNW: 300,
      totalGW: 350,
      totalCBM: 1.25,
    },
  ],
  shipping: {
    portOfLoading: 'Xiamen Port, China',
    portOfDischarge: 'Los Angeles Port, USA',
    vesselName: 'COSCO PACIFIC',
    blNo: 'COSU1234567890',
  },
};

export const BASELINE_SOA_TEMPLATE_SEED: StatementOfAccountData = {
  statementNo: 'SOA-202512-001',
  statementDate: '2025-12-31',
  periodStart: '2025-12-01',
  periodEnd: '2025-12-31',
  company: {
    name: '',
    nameEn: '',
    address: '',
    addressEn: '',
    tel: '',
    email: '',
    accountName: '',
    bankName: '',
    accountNumber: '',
    swiftCode: '',
    bankAddress: '',
    paymentNote: '',
  },
  customer: {
    customerCode: 'CUST-NA-001',
    companyName: 'ABC Trading Corporation',
    address: '123 Main Street, Suite 500, Los Angeles, CA 90001, USA',
    contactPerson: 'John Smith',
    email: 'john.smith@abctrading.com',
    tel: '+1-323-555-0123',
  },
  openingBalance: {
    amount: 0,
    currency: 'USD',
    type: 'debit',
  },
  transactions: [
    { date: '2025-12-01', type: 'invoice', referenceNo: 'INV-20251201-001', description: 'Sales Invoice - Order #12345', debit: 15800, balance: 15800, currency: 'USD' },
    { date: '2025-12-05', type: 'payment', referenceNo: 'PMT-20251205-001', description: 'T/T Payment Received', credit: 8000, balance: 7800, currency: 'USD' },
    { date: '2025-12-15', type: 'invoice', referenceNo: 'INV-20251215-002', description: 'Sales Invoice - Order #12346', debit: 20400, balance: 28200, currency: 'USD' },
    { date: '2025-12-18', type: 'payment', referenceNo: 'PMT-20251218-002', description: 'T/T Payment Received', credit: 7800, balance: 20400, currency: 'USD' },
    { date: '2025-12-20', type: 'invoice', referenceNo: 'INV-20251220-003', description: 'Sales Invoice - Order #12347', debit: 12600, balance: 33000, currency: 'USD' },
    { date: '2025-12-28', type: 'payment', referenceNo: 'PMT-20251228-003', description: 'T/T Payment Received (Partial)', credit: 10000, balance: 23000, currency: 'USD' },
  ],
  closingBalance: {
    amount: 23000,
    currency: 'USD',
    type: 'debit',
  },
  agingAnalysis: {
    current: 12600,
    days30: 10400,
    days60: 0,
    days90Plus: 0,
  },
  remarks: 'Payment terms: 30% deposit, 70% before shipment. Please settle outstanding balance within 30 days. For any queries, please contact our finance department.',
};

export const BASELINE_ING_TEMPLATE_SEED: CustomerInquiryData = {
  inquiryNo: 'ING-NA-260411-9995',
  inquiryDate: '2026-04-11',
  region: 'NA',
  customer: {
    companyName: 'Citybuilders Inc.',
    contactPerson: 'Talal Abi Faraj',
    position: 'Purchasing Manager',
    email: 'talal@citybuilders.biz',
    phone: '+231 6888888',
    address: 'Freeport, Free Trade Zone, Freeport, Liberia',
    country: 'Liberia',
  },
  products: [
    {
      no: 1,
      modelNo: 'TF-20',
      productName: 'Top Freezer Refrigerator 20 cu.ft',
      specification: 'Color: Silver | Capacity: 20 cu.ft | Material: Premium Quality | Warranty: 1 Year | Certification: CE, ISO',
      quantity: 100,
      unit: 'pcs',
      targetPrice: 799,
      currency: 'USD',
    },
    {
      no: 2,
      modelNo: 'TF-18',
      productName: 'Top Freezer Refrigerator 18 cu.ft',
      specification: 'Color: Green | Capacity: 18 cu.ft | Material: Premium Quality | Warranty: 1 Year | Certification: CE, ISO',
      quantity: 100,
      unit: 'pcs',
      targetPrice: 699,
      currency: 'USD',
    },
  ],
  requirements: {
    incoterm: 'CIF',
    locationLabel: 'Destination Port',
    locationValue: 'Monrovia, Liberia',
    finalDestinationPlan: 'Abu Dhabi, UAE',
    deliveryTime: '33 days after downpayment',
    portOfDestination: 'Monrovia, Liberia',
    paymentTerms: buildPaymentTermsText('tt_deposit_balance_before_shipment', 'before_shipment'),
    tradeTerms: 'CIF Monrovia, Liberia',
    paymentMode: 'tt_deposit_balance_before_shipment',
    balanceTrigger: 'before_shipment',
    documentReleasePreference: 'original_bl_required',
    packingRequirements: 'Export cartons with pallet, each carton with SKU label',
    certifications: ['CE', 'ISO'],
    otherRequirements: 'Need logo printing, English manual, and sample approval before mass production',
  },
  templateSettings: {
    productTableColumns: DEFAULT_CUSTOMER_INQUIRY_PRODUCT_TABLE_COLUMNS,
    typography: DEFAULT_CUSTOMER_INQUIRY_TYPOGRAPHY,
  },
  remarks: 'This sample keeps the ING workspace baseline aligned with the current customer-side preview so future admin publishes do not revert column titles, structured trade terms, or product model presentation.',
};

export const buildQrSalesDeptNotesFromInquiry = (inquiry: CustomerInquiryData): string => {
  const rows: Array<{ label: string; value?: string }> = [
    { label: '1. 价格条款', value: inquiry.requirements?.tradeTerms },
    { label: '2. 交期要求', value: inquiry.requirements?.deliveryTime },
    { label: '3. 目的港/交付地点', value: inquiry.requirements?.portOfDestination },
    { label: '4. 付款条款', value: inquiry.requirements?.paymentTerms },
    { label: '5. 包装要求', value: inquiry.requirements?.packingRequirements },
    {
      label: '6. 认证要求',
      value: Array.isArray(inquiry.requirements?.certifications)
        ? inquiry.requirements?.certifications.join('、')
        : inquiry.requirements?.certifications,
    },
    { label: '7. 其他要求', value: inquiry.requirements?.otherRequirements },
  ];

  return rows
    .filter((row) => String(row.value || '').trim())
    .map((row, index) => {
      const fieldKey =
        index === 0 ? 'tradeTerms' :
        index === 1 ? 'deliveryTime' :
        index === 2 ? 'portOfDestination' :
        index === 3 ? 'paymentTerms' :
        index === 4 ? 'packingRequirements' :
        index === 5 ? 'certifications' :
        'otherRequirements';
      const rawValue = String(row.value || '').trim();
      const translated = translateTradingRequirementValue(fieldKey, rawValue) || rawValue;
      return `${row.label}：${translated}`;
    })
    .join('\n\n');
};

export const BASELINE_QT_TEMPLATE_SEED: QuotationData = {
  quotationNo: 'QT-NA-20251210-001',
  quotationDate: '2025-12-10',
  validUntil: '2026-01-10',
  inquiryNo: 'ING-NA-20251210-001',
  region: 'NA',
  company: {
    name: '',
    nameEn: '',
    address: '',
    addressEn: '',
    tel: '',
    fax: '',
    email: '',
    website: '',
  },
  customer: {
    companyName: 'ABC Trading Corporation',
    contactPerson: 'John Smith',
    address: '123 Main Street, Suite 500, Los Angeles, CA 90001, USA',
    email: 'john.smith@abctrading.com',
    phone: '+1-323-555-0123',
  },
  products: [
    { no: 1, productName: 'GFCI Outlet', specification: '20A, 125V, Tamper-Resistant, Weather-Resistant, UL Listed, White with LED', hsCode: '8536.6990', quantity: 5000, unit: 'pcs', unitPrice: 2.85, currency: 'USD', amount: 14250, moq: 3000, leadTime: '25-30 days' },
    { no: 2, productName: 'Weather-Resistant Cover', specification: 'IP66, Single Gang, Clear Polycarbonate', hsCode: '3926.9090', quantity: 2000, unit: 'pcs', unitPrice: 1.65, currency: 'USD', amount: 3300, moq: 1000, leadTime: '20-25 days' },
    { no: 3, productName: 'Decora Wall Plate', specification: 'Screwless Design, UV Resistant, Multi-color', hsCode: '3926.9090', quantity: 3000, unit: 'pcs', unitPrice: 0.95, currency: 'USD', amount: 2850, moq: 2000, leadTime: '20-25 days' },
  ],
  tradeTerms: {
    incoterms: 'FOB Xiamen, China',
    paymentTerms: buildPaymentTermsText('tt_deposit_balance_before_shipment', 'before_shipment'),
    deliveryTime: '25-30 days after receiving deposit',
    packing: 'Export standard carton with wooden pallets, shrink-wrapped',
    portOfLoading: 'Xiamen Port, China',
    portOfDestination: 'Los Angeles Port, USA',
    warranty: '12 months from delivery date against manufacturing defects',
    inspection: "Seller's factory inspection before shipment, buyer has the right to re-inspect upon arrival",
  },
  remarks: 'Above prices are based on current raw material costs and are valid for 30 days. CIF Los Angeles price available upon request. All products come with English manual and installation guide. Free samples available for quality testing.',
  salesPerson: {
    name: '',
    position: 'Senior Sales Manager',
    email: '',
    phone: '',
    whatsapp: '',
  },
  templateSettings: {
    productTableColumns: DEFAULT_QUOTATION_PRODUCT_TABLE_COLUMNS,
  },
};

export const INITIAL_QR_TEXT_OVERRIDES = buildDefaultQuoteRequirementTextOverrides(BASELINE_QR_TEMPLATE_SEED);
export const INITIAL_PR_TEXT_OVERRIDES = {
  ...buildDefaultQuoteRequirementTextOverrides(BASELINE_PR_TEMPLATE_SEED),
  documentTitle: '采购请求单',
  documentTitleEn: 'Procurement Request',
  sourceInquiryLabel: '来源销售合同：',
  customerSectionTitle: '订单客户信息（脱敏）',
  creatorSectionTitle: '采购分配人信息',
  customerRegionLabel: '目标市场：',
  customerIntroText: '本单用于采购员承接销售合同后的供应商拆分与采购分配。页面仅保留采购协同所需的脱敏客户摘要，不展示终端客户敏感资料。',
  creatorRoleLabel: '采购员：',
  creatorDepartmentValue: '采购部',
  productsSectionTitle: '采购分配清单：',
  salesInstructionsTitle: '采购分配说明：',
  customerRequirementsTitle: '采购执行要求',
  customerRequirementsLabel1: '1. 分配原则：',
  customerRequirementsLabel2: '2. 供应商策略：',
  customerRequirementsLabel3: '3. 质量与验收：',
  customerRequirementsLabel4: '4. 包装与交付协同：',
  customerRequirementsLabel5: '5. 特殊说明：',
  salesFallbackNote1: '✓ 本单是 SC 与 CG 之间的桥梁，用于采购员拆分产品并分配供应商',
  salesFallbackNote2: '✓ 一个客户订单可以对应多个供应商，允许基于产品线拆单',
  salesFallbackNote3: '✓ 每个供应商对应一份后续采购合同 CG，务必标明产品和数量归属',
  salesFallbackNote4: '✓ 分配时需综合考虑 MOQ、交期、产能、质量稳定性和历史合作表现',
  salesFallbackNote5: '✓ 所有客户敏感信息在 PR 中必须保持脱敏，仅保留采购执行所需摘要',
  purchaseFeedbackTitle: '采购分配回写：',
  purchaseFeedbackPlaceholder: '（此处用于回写供应商分配结果、拆单结论以及后续生成的 CG 数量/编号）',
  procurementSignatureTitle: '采购主管（审核）：',
  managerSignatureTitle: '采购经理（确认）：',
  footerNote1: '• 本采购请求单为内部协同文件，仅用于销售合同到采购合同的拆单分配',
  footerNote2: '• 页面信息已脱敏，禁止将终端客户敏感资料外发给供应商',
} as const;
