-- ============================================================
-- Migration 014b: Complete Sub-categories & Product Categories
-- Fills all missing entries needed by 015_products_seed.sql
-- ============================================================

-- ── Additional Sub Categories ────────────────────────────────
INSERT INTO product_sub_categories (id, main_category_id, name, sort_order) VALUES
  -- building-materials (extra)
  ('concrete-cement',    'building-materials', 'Concrete & Cement',   3),
  ('drywall',            'building-materials', 'Drywall',             4),
  ('siding',             'building-materials', 'Siding',              5),
  ('masonry',            'building-materials', 'Masonry',             6),
  ('exterior-trim',      'building-materials', 'Exterior Trim',       7),
  ('structural-metal',   'building-materials', 'Structural Metal',    8),
  -- electrical (extra)
  ('electrical-wire',    'electrical', 'Electrical Wire & Cable', 5),
  ('outlets-boxes',      'electrical', 'Outlets & Boxes',         6),
  ('switches',           'electrical', 'Switches',                7),
  ('panels-breakers',    'electrical', 'Panels & Breakers',       8),
  ('conduit-fittings',   'electrical', 'Conduit & Fittings',      9),
  ('portable-power',     'electrical', 'Portable Power',          10),
  ('smart-electrical',   'electrical', 'Smart Electrical',        11),
  -- bathroom (extra)
  ('vanities',           'bathroom', 'Vanities',                  5),
  ('bathroom-sinks-sub', 'bathroom', 'Bathroom Sinks',            6),
  ('bathroom-faucets-sub','bathroom', 'Bathroom Faucets',         7),
  ('showers',            'bathroom', 'Showers',                   8),
  ('bathtubs-sub',       'bathroom', 'Bathtubs',                  9),
  ('bathroom-mirrors',   'bathroom', 'Mirrors',                   10),
  ('bathroom-storage',   'bathroom', 'Storage',                   11),
  ('bath-accessories',   'bathroom', 'Accessories',               12),
  -- door-window (extra)
  ('interior-doors-sub', 'door-window', 'Interior Doors',         5),
  ('door-hardware',      'door-window', 'Door Hardware',          6),
  ('window-hardware',    'door-window', 'Window Hardware',        7),
  ('storm-screen',       'door-window', 'Storm & Screen Doors',   8),
  -- safety (extra)
  ('gloves-sub',         'safety', 'Gloves',                      5),
  ('eye-protection',     'safety', 'Eye Protection',              6),
  ('head-protection',    'safety', 'Head Protection',             7),
  ('hearing-protection', 'safety', 'Hearing Protection',          8),
  ('respiratory',        'safety', 'Respiratory',                 9),
  ('body-protection',    'safety', 'Body Protection',             10),
  ('fall-protection',    'safety', 'Fall Protection',             11),
  ('foot-protection',    'safety', 'Foot Protection',             12),
  ('first-aid',          'safety', 'First Aid',                   13),
  ('safety-signs',       'safety', 'Safety Signs',                14),
  -- flooring (extra)
  ('vinyl-flooring',     'flooring', 'Vinyl Flooring',            5),
  ('floor-tile',         'flooring', 'Floor Tile',                6),
  ('carpet-sub',         'flooring', 'Carpet',                    7),
  ('floor-accessories',  'flooring', 'Accessories & Tools',       8),
  -- heating (extra)
  ('space-heaters',      'heating', 'Space Heaters',              5),
  ('hvac-accessories',   'heating', 'HVAC Accessories',           6),
  ('air-quality',        'heating', 'Air Quality',                7),
  -- kitchen (extra)
  ('kitchen-sinks-sub',  'kitchen', 'Kitchen Sinks',              5),
  ('kitchen-faucets-sub','kitchen', 'Kitchen Faucets',            6),
  ('countertops-sub',    'kitchen', 'Countertops',                7),
  ('backsplash',         'kitchen', 'Backsplash',                 8),
  ('kitchen-islands',    'kitchen', 'Kitchen Islands',            9),
  ('range-hoods',        'kitchen', 'Range Hoods',                10),
  ('cabinet-hardware',   'kitchen', 'Cabinet Hardware',           11),
  ('garbage-disposals',  'kitchen', 'Garbage Disposals',          12),
  ('kitchen-lighting-sub','kitchen', 'Kitchen Lighting',          13),
  -- lighting (extra)
  ('ceiling-fixtures',   'lighting', 'Ceiling Fixtures',          5),
  ('chandeliers',        'lighting', 'Chandeliers',               6),
  ('pendants',           'lighting', 'Pendant Lights',            7),
  ('wall-lighting',      'lighting', 'Wall Lighting',             8),
  ('track-recessed',     'lighting', 'Track & Recessed',          9),
  ('outdoor-wall',       'lighting', 'Outdoor Wall',              10),
  ('landscape',          'lighting', 'Landscape Lighting',        11),
  ('security-lighting',  'lighting', 'Security Lighting',         12),
  ('bulbs',              'lighting', 'Light Bulbs',               13),
  ('lamp-shades',        'lighting', 'Lamp Shades',               14)
ON CONFLICT (id) DO NOTHING;

-- ── Additional Product Categories (3rd level) ─────────────────
INSERT INTO product_categories (id, sub_category_id, name, sort_order) VALUES
  -- building-materials
  ('cement-mix',           'concrete-cement',  'Cement & Concrete Mix',      1),
  ('drywall-panels',       'drywall',          'Drywall Panels',             1),
  ('joint-compound',       'drywall',          'Joint Compound',             2),
  ('fiberglass-insulation','insulation',        'Fiberglass Insulation',      1),
  ('shingles',             'roofing',           'Shingles',                  1),
  ('underlayment',         'roofing',           'Roofing Underlayment',      2),
  ('vinyl-siding',         'siding',            'Vinyl Siding',              1),
  ('brick',                'masonry',           'Brick',                     1),
  ('stone-veneer',         'masonry',           'Stone Veneer',              2),
  ('gutter-systems',       'exterior-trim',     'Gutter Systems',            1),
  ('house-wrap',           'exterior-trim',     'House Wrap',                2),
  ('steel-sheets',         'structural-metal',  'Steel Sheets',              1),
  ('metal-studs',          'structural-metal',  'Metal Studs',               2),
  -- electrical
  ('electrical-wire',      'electrical-wire',   'Electrical Wire',           1),
  ('extension-cords',      'electrical-wire',   'Extension Cords',           2),
  ('wall-outlets',         'outlets-boxes',     'Wall Outlets',              1),
  ('plastic-boxes',        'outlets-boxes',     'Electrical Boxes',          2),
  ('light-switches',       'switches',          'Light Switches',            1),
  ('motion-sensors',       'switches',          'Motion Sensors',            2),
  ('timers',               'switches',          'Timers',                    3),
  ('smart-switches',       'smart-electrical',  'Smart Switches',            1),
  ('breakers',             'panels-breakers',   'Circuit Breakers',          1),
  ('panels',               'panels-breakers',   'Electrical Panels',         2),
  ('pvc-conduit',          'conduit-fittings',  'PVC Conduit',               1),
  ('portable-generators',  'portable-power',    'Portable Generators',       1),
  ('batteries',            'portable-power',    'Batteries',                 2),
  ('surge-protectors',     'portable-power',    'Surge Protectors',          3),
  ('wired-doorbells',      'smart-electrical',  'Wired Doorbells',           2),
  -- bathroom
  ('two-piece-toilets',    'toilets',           'Two-Piece Toilets',         1),
  ('one-piece-toilets',    'toilets',           'One-Piece Toilets',         2),
  ('single-vanities',      'vanities',          'Single Vanities',           1),
  ('double-vanities',      'vanities',          'Double Vanities',           2),
  ('vanity-tops',          'vanities',          'Vanity Tops',               3),
  ('bathroom-sinks',       'bathroom-sinks-sub','Bathroom Sinks',            1),
  ('bathroom-faucets',     'bathroom-faucets-sub','Bathroom Faucets',        1),
  ('shower-doors',         'showers',           'Shower Doors',              1),
  ('shower-heads',         'showers',           'Shower Heads',              2),
  ('complete-shower-systems','showers',         'Complete Shower Systems',   3),
  ('bathtubs',             'bathtubs-sub',      'Bathtubs',                  1),
  ('framed-mirrors',       'bathroom-mirrors',  'Framed Mirrors',            1),
  ('led-mirrors',          'bathroom-mirrors',  'LED Mirrors',               2),
  ('medicine-cabinets',    'bathroom-storage',  'Medicine Cabinets',         1),
  ('linen-cabinets',       'bathroom-storage',  'Linen Cabinets',            2),
  ('towel-bars',           'bath-accessories',  'Towel Bars',                1),
  ('toilet-paper-holders', 'bath-accessories',  'Toilet Paper Holders',      2),
  ('exhaust-fans',         'bath-accessories',  'Exhaust Fans',              3),
  -- door-window
  ('panel-doors',          'interior-doors-sub','Panel Doors',               1),
  ('barn-doors',           'interior-doors-sub','Barn Doors',                2),
  ('entry-doors',          'exterior-doors',    'Entry Doors',               1),
  ('patio-doors',          'exterior-doors',    'Patio Doors',               2),
  ('double-hung-windows',  'windows',           'Double Hung Windows',       1),
  ('casement-windows',     'windows',           'Casement Windows',          2),
  ('door-knobs',           'door-hardware',     'Door Knobs',                1),
  ('door-levers',          'door-hardware',     'Door Levers',               2),
  ('deadbolts',            'door-hardware',     'Deadbolts',                 3),
  ('interior-hinges',      'door-hardware',     'Hinges',                    4),
  ('door-stops',           'door-hardware',     'Door Stops & Closers',      5),
  ('door-closers',         'door-hardware',     'Door Closers',              6),
  ('door-weather-strip',   'door-hardware',     'Weather Stripping',         7),
  ('window-locks',         'window-hardware',   'Window Locks',              1),
  ('sectional-garage-doors','garage-doors',     'Sectional Garage Doors',    1),
  ('garage-openers',       'garage-doors',      'Garage Door Openers',       2),
  ('full-view-storm',      'storm-screen',      'Storm Doors',               1),
  -- safety
  ('work-gloves',          'gloves-sub',        'Work Gloves',               1),
  ('chemical-gloves',      'gloves-sub',        'Chemical Gloves',           2),
  ('safety-glasses',       'eye-protection',    'Safety Glasses',            1),
  ('face-shields',         'eye-protection',    'Face Shields',              2),
  ('goggles',              'eye-protection',    'Goggles',                   3),
  ('hard-hats',            'head-protection',   'Hard Hats',                 1),
  ('ear-plugs',            'hearing-protection','Ear Plugs',                 1),
  ('ear-muffs',            'hearing-protection','Ear Muffs',                 2),
  ('dust-masks',           'respiratory',       'Dust Masks',                1),
  ('respirators',          'respiratory',       'Respirators',               2),
  ('safety-vests',         'body-protection',   'Safety Vests',              1),
  ('coveralls',            'body-protection',   'Coveralls',                 2),
  ('safety-harness',       'fall-protection',   'Safety Harnesses',          1),
  ('lanyards',             'fall-protection',   'Lanyards',                  2),
  ('safety-boots',         'foot-protection',   'Safety Boots',              1),
  ('first-aid-kits',       'first-aid',         'First Aid Kits',            1),
  ('warning-signs',        'safety-signs',      'Warning Signs',             1),
  -- flooring
  ('solid-hardwood',       'hardwood',          'Solid Hardwood',            1),
  ('engineered-hardwood',  'hardwood',          'Engineered Hardwood',       2),
  ('wood-look-laminate',   'laminate',          'Wood Look Laminate',        1),
  ('stone-look-laminate',  'laminate',          'Stone Look Laminate',       2),
  ('lvp',                  'vinyl-flooring',    'Luxury Vinyl Plank (LVP)',  1),
  ('lvt',                  'vinyl-flooring',    'Luxury Vinyl Tile (LVT)',   2),
  ('sheet-vinyl',          'vinyl-flooring',    'Sheet Vinyl',               3),
  ('ceramic-tile',         'floor-tile',        'Ceramic Tile',              1),
  ('porcelain-tile',       'floor-tile',        'Porcelain Tile',            2),
  ('carpet-rolls',         'carpet-sub',        'Carpet Rolls',              1),
  ('carpet-tiles',         'carpet-sub',        'Carpet Tiles',              2),
  ('foam-underlayment',    'floor-accessories', 'Foam Underlayment',         1),
  ('indoor-rugs',          'floor-accessories', 'Indoor Rugs',               2),
  ('baseboards',           'floor-accessories', 'Baseboards',                3),
  ('quarter-round',        'floor-accessories', 'Quarter Round',             4),
  ('tile-adhesive',        'floor-accessories', 'Tile Adhesive',             5),
  ('flooring-installation','floor-accessories', 'Installation Tools',        6),
  -- heating
  ('central-ac-units',     'heat-pumps',        'Central AC Units',          1),
  ('air-heat-pumps',       'heat-pumps',        'Air Source Heat Pumps',     2),
  ('gas-furnaces',         'furnaces',          'Gas Furnaces',              1),
  ('electric-furnaces',    'furnaces',          'Electric Furnaces',         2),
  ('programmable-thermostats','thermostats',    'Programmable Thermostats',  1),
  ('smart-thermostats',    'thermostats',       'Smart Thermostats',         2),
  ('electric-heaters',     'space-heaters',     'Electric Space Heaters',    1),
  ('propane-heaters',      'space-heaters',     'Propane Heaters',           2),
  ('ceiling-fans',         'fans',              'Ceiling Fans',              1),
  ('box-fans',             'fans',              'Box Fans',                  2),
  ('furnace-filters',      'hvac-accessories',  'Furnace Filters',           1),
  ('flex-duct',            'hvac-accessories',  'Flexible Duct',             2),
  ('registers',            'hvac-accessories',  'Registers & Grilles',       3),
  ('portable-humidifiers', 'air-quality',       'Humidifiers',               1),
  ('hepa-purifiers',       'air-quality',       'Air Purifiers',             2),
  -- kitchen
  ('base-cabinets',        'cabinets',          'Base Cabinets',             1),
  ('wall-cabinets',        'cabinets',          'Wall Cabinets',             2),
  ('pantry-cabinets',      'cabinets',          'Pantry Cabinets',           3),
  ('undermount-sinks',     'kitchen-sinks-sub', 'Undermount Sinks',          1),
  ('drop-in-sinks',        'kitchen-sinks-sub', 'Drop-In Sinks',             2),
  ('farmhouse-sinks',      'kitchen-sinks-sub', 'Farmhouse Sinks',           3),
  ('pull-down-faucets',    'kitchen-faucets-sub','Pull-Down Faucets',        1),
  ('commercial-faucets',   'kitchen-faucets-sub','Commercial Faucets',       2),
  ('laminate-countertops', 'countertops-sub',   'Laminate Countertops',      1),
  ('butcher-block',        'countertops-sub',   'Butcher Block',             2),
  ('subway-tile',          'backsplash',        'Subway Tile',               1),
  ('mosaic-tile',          'backsplash',        'Mosaic Tile',               2),
  ('portable-islands',     'kitchen-islands',   'Portable Islands',          1),
  ('under-cabinet-hoods',  'range-hoods',       'Under-Cabinet Hoods',       1),
  ('wall-mount-hoods',     'range-hoods',       'Wall-Mount Hoods',          2),
  ('cabinet-pulls',        'cabinet-hardware',  'Cabinet Pulls',             1),
  ('cabinet-knobs',        'cabinet-hardware',  'Cabinet Knobs',             2),
  ('continuous-feed',      'garbage-disposals', 'Continuous Feed Disposals', 1),
  ('pendant-lights',       'kitchen-lighting-sub','Pendant Lights',          1),
  ('under-cabinet-lighting','kitchen-lighting-sub','Under Cabinet Lighting', 2),
  -- lighting
  ('flush-mount',          'ceiling-fixtures',  'Flush Mount',               1),
  ('semi-flush',           'ceiling-fixtures',  'Semi-Flush Mount',          2),
  ('traditional-chandeliers','chandeliers',     'Traditional Chandeliers',   1),
  ('modern-chandeliers',   'chandeliers',       'Modern Chandeliers',        2),
  ('mini-pendants',        'pendants',          'Mini Pendants',             1),
  ('multi-light-pendants', 'pendants',          'Multi-Light Pendants',      2),
  ('indoor-sconces',       'wall-lighting',     'Indoor Sconces',            1),
  ('fixed-track',          'track-recessed',    'Fixed Track Lighting',      1),
  ('led-recessed',         'track-recessed',    'LED Recessed Lights',       2),
  ('porch-lights',         'outdoor-wall',      'Porch Lights',              1),
  ('landscape-lights',     'landscape',         'Landscape Lights',          1),
  ('security-lights',      'security-lighting', 'Security Lights',           1),
  ('led-bulbs',            'bulbs',             'LED Bulbs',                 1),
  ('cfl-bulbs',            'bulbs',             'CFL Bulbs',                 2),
  ('smart-bulbs',          'smart-lighting',    'Smart Bulbs',               1),
  ('drum-shades',          'lamp-shades',       'Drum Shades',               1)
ON CONFLICT (id) DO NOTHING;
