export const projectId = "oaavirpytvemskjooeyg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hYXZpcnB5dHZlbXNram9vZXlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyODc2NjUsImV4cCI6MjA4Nzg2MzY2NX0.AgKVC_Z_UmMLJs_j8XwVKnAMZhwPJjOLd0V7z0xQ5-I"
export const supabaseUrl = "https://oaavirpytvemskjooeyg.supabase.co"