// 📋 单证服务 (Documentation Service)
// 处理单证的自动生成、上传、审批等业务逻辑

import { eventBus, type BusinessEvent, type EventPayload } from '../business-event-bus';
import { createClient } from '@supabase/supabase-js';

// ============ 类型定义 ============
interface DocumentInstance {
  instance_id: string;
  order_id: string;
  doc_id: string;
  status: 'pending' | 'auto_generated' | 'uploaded' | 'reviewing' | 'approved' | 'rejected' | 'na' | 'overdue';
  generation_type: 'auto' | 'manual' | 'external' | 'template';
  upload_date?: string;
  upload_by?: string;
  reviewer?: string;
  review_date?: string;
  approve_date?: string;
  version: number;
}

interface Contract {
  order_id: string;
  contract_no: string;
  customer_name: string;
  total_value: number;
  currency: string;
  incoterm: 'EXW' | 'FCA' | 'FOB' | 'CFR' | 'CIF';
  payment_term: string;
  signed_date: string;
  sales_rep: string;
}

// ============ 单证服务类 ============
class DocumentationService {
  private supabase: ReturnType<typeof createClient> | null = null;
  private isInitialized = false;

  constructor() {
    // 不在构造函数中订阅，避免重复订阅
  }

  /**
   * 初始化服务
   */
  init(supabaseUrl: string, supabaseKey: string) {
    if (this.isInitialized) {
      console.warn('⚠️ [DocumentationService] 服务已初始化，跳过重复初始化');
      return;
    }

    this.supabase = createClient(supabaseUrl, supabaseKey);
    this.subscribeToBusinessEvents();
    this.isInitialized = true;
    
    console.log('✅ [DocumentationService] 服务已初始化');
  }

  /**
   * 订阅业务事件
   */
  private subscribeToBusinessEvents() {
    console.log('📡 [DocumentationService] 开始订阅业务事件...');

    // 1️⃣ 监听：合同签订
    eventBus.subscribe('CONTRACT_SIGNED', async (payload: EventPayload<Contract>) => {
      console.log('📋 [单证系统] 检测到合同签订事件，开始处理...');
      
      try {
        // 创建单证任务
        await this.createDocumentationTask(payload.orderId, payload.contractNo || payload.data.contract_no);
        
        // 自动生成D02
        await this.generateD02(payload.data);
        
        // 根据Incoterm自动判断并生成D04/D10
        await this.autoGenerateWaivers(payload.data);
        
        console.log(`✅ [单证系统] 合同签订事件处理完成: ${payload.orderId}`);
      } catch (error) {
        console.error('❌ [单证系统] 处理合同签订事件失败:', error);
      }
    });

    // 2️⃣ 监听：采购付款
    eventBus.subscribe('PROCUREMENT_PAID', async (payload) => {
      console.log('📋 [单证系统] 检测到采购付款事件，生成D07...');
      
      try {
        await this.generateD07(payload.orderId, payload.data);
        console.log(`✅ [单证系统] D07生成完成: ${payload.orderId}`);
      } catch (error) {
        console.error('❌ [单证系统] 生成D07失败:', error);
      }
    });

    // 3️⃣ 监听：出货通知
    eventBus.subscribe('SHIPPING_NOTICE_ISSUED', async (payload) => {
      console.log('📋 [单证系统] 检测到出货通知，提醒物流部上传D03...');
      
      try {
        await this.remindUploadD03(payload.orderId);
        console.log(`✅ [单证系统] D03上传提醒已发送: ${payload.orderId}`);
      } catch (error) {
        console.error('❌ [单证系统] D03提醒失败:', error);
      }
    });

    // 4️⃣ 监听：报关完成
    eventBus.subscribe('CUSTOMS_CLEARED', async (payload) => {
      console.log('📋 [单证系统] 检测到报关完成，处理D05/D06/D08...');
      
      try {
        await this.remindUploadD05(payload.orderId);
        await this.remindUploadD06(payload.orderId);
        await this.autoGenerateD08(payload.orderId, payload.data);
        console.log(`✅ [单证系统] 报关单证处理完成: ${payload.orderId}`);
      } catch (error) {
        console.error('❌ [单证系统] 报关单证处理失败:', error);
      }
    });

    // 5️⃣ 监听：开船
    eventBus.subscribe('VESSEL_DEPARTED', async (payload) => {
      console.log('📋 [单证系统] 检测到开船，提醒货代上传D09...');
      
      try {
        await this.remindUploadD09(payload.orderId);
        console.log(`✅ [单证系统] D09上传提醒已发送: ${payload.orderId}`);
      } catch (error) {
        console.error('❌ [单证系统] D09提醒失败:', error);
      }
    });

    // 6️⃣ 监听：收汇
    eventBus.subscribe('PAYMENT_RECEIVED', async (payload) => {
      console.log('📋 [单证系统] 检测到收汇，关联D11...');
      
      try {
        await this.linkD11(payload.orderId, payload.data);
        console.log(`✅ [单证系统] D11关联完成: ${payload.orderId}`);
      } catch (error) {
        console.error('❌ [单证系统] D11关联失败:', error);
      }
    });

    // 7️⃣ 监听：结汇
    eventBus.subscribe('FX_SETTLED', async (payload) => {
      console.log('📋 [单证系统] 检测到结汇，处理D12/D13/D01...');
      
      try {
        await this.linkD12(payload.orderId, payload.data);
        await this.generateD13(payload.orderId, payload.data);
        
        // 检查是否可以生成D01
        await this.checkAndGenerateD01(payload.orderId);
        
        console.log(`✅ [单证系统] 结汇单证处理完成: ${payload.orderId}`);
      } catch (error) {
        console.error('❌ [单证系统] 结汇单证处理失败:', error);
      }
    });

    console.log('✅ [DocumentationService] 业务事件订阅完成');
  }

  /**
   * 创建单证任务（13项单证）
   */
  async createDocumentationTask(orderId: string, contractNo: string) {
    if (!this.supabase) {
      console.error('❌ Supabase未初始化');
      return;
    }

    console.log(`📋 为订单 ${orderId} 创建13项单证任务...`);

    const docIds = ['D01', 'D02', 'D03', 'D04', 'D05', 'D06', 'D07', 'D08', 'D09', 'D10', 'D11', 'D12', 'D13'];
    
    const instances = docIds.map(docId => ({
      instance_id: `${orderId}-${docId}`,
      order_id: orderId,
      doc_id: docId,
      status: 'pending',
      generation_type: this.getGenerationType(docId),
      version: 1
    }));

    const { error } = await this.supabase
      .from('document_instances')
      .insert(instances);

    if (error) {
      console.error('❌ 创建单证任务失败:', error);
      throw error;
    }

    console.log(`✅ 已为订单 ${orderId} 创建13项单证任务`);
  }

  /**
   * 获取单证的生成方式
   */
  private getGenerationType(docId: string): 'auto' | 'manual' | 'external' {
    const autoGenDocs = ['D01', 'D02', 'D04', 'D07', 'D08', 'D10', 'D13'];
    const externalDocs = ['D03', 'D05', 'D06', 'D09', 'D11', 'D12'];
    
    if (autoGenDocs.includes(docId)) return 'auto';
    if (externalDocs.includes(docId)) return 'external';
    return 'manual';
  }

  /**
   * 自动生成D02（销售合同）
   */
  async generateD02(contractData: Contract) {
    console.log(`📄 自动生成D02 - 销售合同: ${contractData.contract_no}`);
    
    // TODO: 使用文档生成引擎生成PDF
    // const pdfFile = await documentGenerator.generate('D02', contractData);
    
    // 模拟生成
    await this.updateDocumentStatus(contractData.order_id, 'D02', 'auto_generated', 'system');
    
    console.log(`✅ D02已自动生成`);
  }

  /**
   * 根据Incoterm自动判断并生成免责声明
   */
  async autoGenerateWaivers(contractData: Contract) {
    console.log(`🔍 根据Incoterm (${contractData.incoterm}) 判断免责声明...`);

    // D04 国内运费免责声明
    if (['FOB', 'CFR', 'CIF'].includes(contractData.incoterm)) {
      console.log(`📄 自动生成D04 - 国内运费免责声明 (${contractData.incoterm})`);
      await this.updateDocumentStatus(contractData.order_id, 'D04', 'auto_generated', 'system');
    } else {
      console.log(`⏭️ ${contractData.incoterm}条款不需要D04`);
      await this.updateDocumentStatus(contractData.order_id, 'D04', 'na', 'system');
    }

    // D10 国际运费免责声明
    if (['EXW', 'FCA', 'FOB'].includes(contractData.incoterm)) {
      console.log(`📄 自动生成D10 - 国际运费免责声明 (${contractData.incoterm})`);
      await this.updateDocumentStatus(contractData.order_id, 'D10', 'auto_generated', 'system');
    } else {
      console.log(`⏭️ ${contractData.incoterm}条款不需要D10`);
      await this.updateDocumentStatus(contractData.order_id, 'D10', 'na', 'system');
    }
  }

  /**
   * 生成D07（采购发票）
   */
  async generateD07(orderId: string, procurementData: any) {
    console.log(`📄 自动生成D07 - 采购发票: ${orderId}`);
    
    // TODO: 使用文档生成引擎
    await this.updateDocumentStatus(orderId, 'D07', 'auto_generated', 'system');
    
    console.log(`✅ D07已自动生成`);
  }

  /**
   * 提醒上传D03（国内运输单据）
   */
  async remindUploadD03(orderId: string) {
    console.log(`📢 提醒物流部上传D03: ${orderId}`);
    
    // TODO: 发送通知给物流部
    // await notificationService.send('logistics', `订单${orderId}需要上传D03国内运输单据`);
    
    await this.updateDocumentStatus(orderId, 'D03', 'pending', 'system');
  }

  /**
   * 提醒上传D05（报关单）
   */
  async remindUploadD05(orderId: string) {
    console.log(`📢 提醒报关行上传D05: ${orderId}`);
    
    // TODO: 发送通知给报关行
    await this.updateDocumentStatus(orderId, 'D05', 'pending', 'system');
  }

  /**
   * 提醒上传D06（委托报关合同）
   */
  async remindUploadD06(orderId: string) {
    console.log(`📢 提醒报关行上传D06: ${orderId}`);
    
    // TODO: 发送通知给报关行
    await this.updateDocumentStatus(orderId, 'D06', 'pending', 'system');
  }

  /**
   * 自动生成D08（报关费用免责声明）
   */
  async autoGenerateD08(orderId: string, customsData: any) {
    console.log(`📄 自动生成D08 - 报关费用免责声明: ${orderId}`);
    
    // TODO: 根据合同条款判断是否需要
    // 简化处理：默认不需要
    await this.updateDocumentStatus(orderId, 'D08', 'na', 'system');
  }

  /**
   * 提醒上传D09（国际运费发票）
   */
  async remindUploadD09(orderId: string) {
    console.log(`📢 提醒货代上传D09: ${orderId}`);
    
    // TODO: 发送通知给货代
    await this.updateDocumentStatus(orderId, 'D09', 'pending', 'system');
  }

  /**
   * 关联D11（收汇水单）
   */
  async linkD11(orderId: string, paymentData: any) {
    console.log(`🔗 关联D11 - 收汇水单: ${orderId}`);
    
    // TODO: 将财务模块上传的收汇水单关联到单证系统
    await this.updateDocumentStatus(orderId, 'D11', 'uploaded', paymentData.operator || 'finance');
  }

  /**
   * 关联D12（结汇水单）
   */
  async linkD12(orderId: string, settlementData: any) {
    console.log(`🔗 关联D12 - 结汇水单: ${orderId}`);
    
    // TODO: 将财务模块上传的结汇水单关联到单证系统
    await this.updateDocumentStatus(orderId, 'D12', 'uploaded', settlementData.operator || 'finance');
  }

  /**
   * 生成D13（出口退税收汇凭证表）
   */
  async generateD13(orderId: string, settlementData: any) {
    console.log(`📄 自动生成D13 - 出口退税收汇凭证表: ${orderId}`);
    
    // TODO: 根据D12数据生成D13
    await this.updateDocumentStatus(orderId, 'D13', 'auto_generated', 'system');
    
    console.log(`✅ D13已自动生成`);
  }

  /**
   * 检查并生成D01（出口退税申报表）
   */
  async checkAndGenerateD01(orderId: string) {
    console.log(`🔍 检查D01依赖：D05 + D11 + D12 + D13...`);
    
    const deps = await this.checkDependencies(orderId, ['D05', 'D11', 'D12', 'D13']);
    
    if (deps.allCompleted) {
      console.log('✅ D01依赖已齐全，自动生成退税申报表...');
      
      // TODO: 生成D01
      await this.updateDocumentStatus(orderId, 'D01', 'auto_generated', 'system');
      
      // 发布事件：单证齐全可退税
      eventBus.publish({
        eventType: 'DOCS_READY_FOR_TAX_REFUND',
        orderId: orderId,
        timestamp: new Date().toISOString(),
        data: { message: 'All 13 documents completed' },
        operator: 'system'
      });
      
      console.log(`✅ D01已自动生成，退税申报可开始`);
    } else {
      console.log(`⏳ D01依赖未齐全，缺少: ${deps.missing.join(', ')}`);
    }
  }

  /**
   * 检查单证依赖
   */
  private async checkDependencies(orderId: string, docIds: string[]) {
    if (!this.supabase) {
      return { allCompleted: false, missing: docIds };
    }

    const { data, error } = await this.supabase
      .from('document_instances')
      .select('doc_id, status')
      .eq('order_id', orderId)
      .in('doc_id', docIds);

    if (error || !data) {
      console.error('❌ 检查依赖失败:', error);
      return { allCompleted: false, missing: docIds };
    }

    const completed = data
      .filter(d => ['approved', 'auto_generated', 'uploaded'].includes(d.status))
      .map(d => d.doc_id);
    
    const missing = docIds.filter(id => !completed.includes(id));
    
    return {
      allCompleted: missing.length === 0,
      missing
    };
  }

  /**
   * 更新单证状态
   */
  async updateDocumentStatus(
    orderId: string,
    docId: string,
    status: DocumentInstance['status'],
    operator: string
  ) {
    if (!this.supabase) {
      console.error('❌ Supabase未初始化');
      return;
    }

    const { error } = await this.supabase
      .from('document_instances')
      .update({
        status,
        upload_by: operator,
        upload_date: new Date().toISOString()
      })
      .eq('instance_id', `${orderId}-${docId}`);

    if (error) {
      console.error(`❌ 更新单证状态失败 (${docId}):`, error);
      throw error;
    }

    console.log(`✅ 单证状态已更新: ${orderId}-${docId} → ${status}`);
  }

  /**
   * 获取订单的所有单证
   */
  async getOrderDocuments(orderId: string): Promise<DocumentInstance[]> {
    if (!this.supabase) {
      console.error('❌ Supabase未初始化');
      return [];
    }

    const { data, error } = await this.supabase
      .from('document_instances')
      .select('*')
      .eq('order_id', orderId)
      .order('doc_id');

    if (error) {
      console.error('❌ 获取单证列表失败:', error);
      return [];
    }

    return data || [];
  }
}

// ============ 导出单例 ============
export const documentationService = new DocumentationService();

// ============ 导出类型 ============
export type { DocumentInstance, Contract };
