-- Complete bilingual Chinese/English category names for all storefront levels.
-- This fills remaining L2/L3 storefront categories whose name still matched name_en.

with translated_category_names(english_name, zh_name) as (
  values
  ('3-Piece Packages', '3件套装'),
  ('4-Piece Packages', '4件套装'),
  ('AC Filters', '空调滤网'),
  ('AC3 Laminate', 'AC3强化地板'),
  ('AC4 Laminate', 'AC4强化地板'),
  ('Address Plaques', '地址牌'),
  ('Alarm Systems', '报警系统'),
  ('Alcove Tubs', '嵌入式浴缸'),
  ('Aluminum Gutters', '铝制檐槽'),
  ('Angle Grinders', '角磨机'),
  ('Appliance Cleaner', '家电清洁剂'),
  ('Asphalt Shingles', '沥青瓦'),
  ('Augers', '管道疏通器'),
  ('Base Cabinets', '地柜'),
  ('Batch Feed Disposals', '批量进料垃圾处理器'),
  ('Bath Bars', '浴室灯条'),
  ('Bathroom Fans', '浴室风扇'),
  ('Bathroom Heaters', '浴室取暖器'),
  ('Belt Sanders', '带式砂光机'),
  ('Berber Carpet', '柏柏尔地毯'),
  ('Bidets', '智能坐便器'),
  ('Bike Racks', '自行车架'),
  ('Bird Baths', '鸟浴盆'),
  ('Brad Nailers', '直钉枪'),
  ('Built-In Dishwashers', '嵌入式洗碗机'),
  ('Built-In Microwaves', '嵌入式微波炉'),
  ('Butcher Blocks', '实木砧板台面'),
  ('Cabinet Doors', '柜门'),
  ('Cable', '钢缆'),
  ('Casters', '脚轮'),
  ('Cedar & Redwood', '雪松与红木'),
  ('Cement Mix', '水泥混合料'),
  ('Central AC', '中央空调'),
  ('Ceramic Pots', '陶瓷花盆'),
  ('Chain & Rope', '链条与绳索'),
  ('Chest Freezers', '卧式冷柜'),
  ('Chisels', '凿子'),
  ('Circular Saws', '圆锯'),
  ('Clearance Items', '清仓商品'),
  ('Closet Organizers', '衣柜收纳'),
  ('Closet Rods', '衣柜挂杆'),
  ('Coat Hooks', '衣帽钩'),
  ('Coaxial Cable', '同轴电缆'),
  ('Commercial Freezers & Ice Makers', '商用冷柜与制冰机'),
  ('Compact Dishwashers', '紧凑型洗碗机'),
  ('Complete Kitchen Suites', '完整厨房套装'),
  ('Composite Decking', '复合地板'),
  ('Concrete Tools', '混凝土工具'),
  ('Connectors', '连接件'),
  ('Continuous Feed Disposals', '连续进料垃圾处理器'),
  ('Copper Pipe', '铜管'),
  ('Cordless Drills', '无绳电钻'),
  ('Cork Underlayment', '软木垫层'),
  ('Corner Bead', '护角条'),
  ('Corrugated Metal', '波纹金属板'),
  ('Countertop Microwaves', '台式微波炉'),
  ('Cutting Boards', '砧板'),
  ('Dish Racks', '碗碟架'),
  ('Dishwasher Parts', '洗碗机配件'),
  ('Disposal Accessories', '垃圾处理器配件'),
  ('Door Hinges', '门铰链'),
  ('Double Sink Vanities', '双盆浴室柜'),
  ('Downspouts', '落水管'),
  ('Drain Parts', '排水配件'),
  ('Drainage Pipe', '排水管'),
  ('Drawer Dishwashers', '抽屉式洗碗机'),
  ('Drawer Organizers', '抽屉收纳盒'),
  ('Drop-In Sinks', '台上盆'),
  ('Dryer Parts', '烘干机配件'),
  ('Dual Fuel Ranges', '双燃料炉灶'),
  ('Duct Fittings', '风管配件'),
  ('Duct Pipe', '风管'),
  ('Ductless Mini-Split', '无风管分体空调'),
  ('Ductwork & Vents', '风管与通风口'),
  ('Electric Cooktops', '电陶炉灶'),
  ('Electric Fireplaces', '电壁炉'),
  ('Electric Furnaces', '电暖炉'),
  ('Electric Pressure Washers', '电动高压清洗机'),
  ('Electric Ranges', '电炉灶'),
  ('Exhaust Fan Lights', '排风扇灯'),
  ('Extension Ladders', '伸缩梯'),
  ('Exterior Trim', '外墙装饰线条'),
  ('Farmhouse Sinks', '农舍水槽'),
  ('Fasteners & Anchors', '紧固件与锚栓'),
  ('Faucet Parts', '龙头配件'),
  ('Fertilizers & Chemicals', '肥料与园艺化学品'),
  ('Fiber Cement', '纤维水泥板'),
  ('Fill Valves', '进水阀'),
  ('Flappers', '马桶挡水阀'),
  ('Flashing Tape', '泛水胶带'),
  ('Floor Cleaners', '地板清洁剂'),
  ('Floor Nailers', '地板钉枪'),
  ('Floor Vents', '地板通风口'),
  ('Flower Seeds', '花卉种子'),
  ('Foam Board', '泡沫板'),
  ('Foam Underlayment', '泡沫垫层'),
  ('Framed Mirrors', '带框镜'),
  ('Frameless Doors', '无框门'),
  ('Frameless Mirrors', '无框镜'),
  ('Freestanding Tubs', '独立式浴缸'),
  ('Furnace Filters', '暖炉滤网'),
  ('Furniture Glides', '家具脚垫'),
  ('Furniture Legs', '家具脚'),
  ('Garden Décor', '花园装饰'),
  ('Garden Flags', '花园旗'),
  ('Garden Tools', '园艺工具'),
  ('Gas Cooktops', '燃气炉灶'),
  ('Gas Fireplaces', '燃气壁炉'),
  ('Gas Furnaces', '燃气暖炉'),
  ('Gas Pressure Washers', '燃气高压清洗机'),
  ('Gas Ranges', '燃气炉灶'),
  ('Gate Handles', '门闸把手'),
  ('Gate Hinges', '门闸铰链'),
  ('Gate Latches', '门闸插销'),
  ('Glass Tile', '玻璃瓷砖'),
  ('Granite', '花岗岩'),
  ('Grass Seed', '草籽'),
  ('Grilles', '格栅'),
  ('Grout Tools', '填缝工具'),
  ('Gutter Guards', '檐槽护网'),
  ('Halogen Bulbs', '卤素灯泡'),
  ('Hammer Drills', '冲击钻'),
  ('Hampers', '洗衣篮'),
  ('Hand Tool Sets', '手动工具套装'),
  ('Hanging Baskets', '吊篮'),
  ('Hardwood Boards', '硬木板'),
  ('Hardwood Plywood', '硬木胶合板'),
  ('Hasps', '搭扣'),
  ('Heat Pump', '热泵'),
  ('Hedge Trimmers', '绿篱修剪机'),
  ('HEPA Filters', 'HEPA滤网'),
  ('Hinges & Latches', '铰链与插销'),
  ('Hoes', '锄头'),
  ('Hooks & Hangers', '挂钩与挂架'),
  ('Hooks & Racks', '挂钩与置物架'),
  ('House Numbers', '门牌号'),
  ('House Wrap', '建筑防水透气膜'),
  ('Humidifiers', '加湿器'),
  ('HVAC Filters', '暖通空调滤网'),
  ('Ice Makers', '制冰机'),
  ('Indoor Ceiling Fans', '室内吊扇'),
  ('Indoor Extension Cords', '室内延长线'),
  ('Induction Cooktops', '电磁炉灶'),
  ('Infrared Heaters', '红外取暖器'),
  ('Insulation Accessories', '保温隔热配件'),
  ('Intercom Systems', '对讲系统'),
  ('Inverter Generators', '变频发电机'),
  ('Ironing Boards', '熨衣板'),
  ('Kitchen Carts', '厨房推车'),
  ('Kitchen Fans', '厨房风扇'),
  ('Kitchen Islands', '厨房岛台'),
  ('Knife Blocks', '刀座'),
  ('Ladders & Scaffolding', '梯子与脚手架'),
  ('Laser Levels', '激光水平仪'),
  ('Latches', '插销'),
  ('Laundry Baskets', '洗衣篮'),
  ('Laundry Pairs', '洗烘套装'),
  ('Laundry Storage', '洗衣房收纳'),
  ('Lawn Edgers', '草坪修边机'),
  ('Lawn Fertilizer', '草坪肥料'),
  ('Leaf Blowers', '吹叶机'),
  ('Lighted Mirrors', '带灯镜'),
  ('Lockers', '储物柜'),
  ('Luxury Vinyl Plank', '高端乙烯基地板'),
  ('Mailbox Letters', '邮箱字母'),
  ('Manual Thermostats', '手动温控器'),
  ('Marble', '大理石'),
  ('MDF Boards', 'MDF板材'),
  ('Mechanics Sets', '机修工具套装'),
  ('Metal Flashing', '金属泛水板'),
  ('Metal Framing', '金属龙骨'),
  ('Metal Roofing', '金属屋面'),
  ('Metal Shelving', '金属置物架'),
  ('Metal Trim', '金属收边条'),
  ('Microwave Parts', '微波炉配件'),
  ('Miter Saws', '斜切锯'),
  ('Moisture Barriers', '防潮层'),
  ('Mortar Mix', '砂浆混合料'),
  ('Motion Sensors', '运动传感器'),
  ('Numbers & Letters', '门牌数字与字母'),
  ('One-Piece Toilets', '连体马桶'),
  ('Orbital Sanders', '轨道砂光机'),
  ('OSB Sheathing', 'OSB护墙板'),
  ('Outdoor Ceiling Fans', '户外吊扇'),
  ('Outdoor Extension Cords', '户外延长线'),
  ('Over-the-Range Microwaves', '炉灶上方微波炉'),
  ('Overhead Storage', '顶置收纳'),
  ('Padlocks', '挂锁'),
  ('Panel Accessories', '配电箱配件'),
  ('Pantry Cabinets', '食品储藏柜'),
  ('Pantry Shelving', '食品储藏架'),
  ('Particleboard', '刨花板'),
  ('Pedestal Sinks', '立柱盆'),
  ('Pegboards', '洞洞板'),
  ('Pest Control', '虫害防治'),
  ('PEX Manifolds', 'PEX分水器'),
  ('PEX Pipe', 'PEX管'),
  ('Phone Cable', '电话线'),
  ('Pipe Cutters', '切管器'),
  ('Pipe Fittings', '管件'),
  ('Pipe Wrenches', '管钳'),
  ('Pivot Shower Doors', '枢轴淋浴门'),
  ('Plants', '植物'),
  ('Plastic Planters', '塑料种植盆'),
  ('Plumbers Putty', '管道工密封泥'),
  ('Plumbing Repair & Maintenance', '管道维修与维护'),
  ('Plumbing Tools', '管道工具'),
  ('Plungers', '皮搋子'),
  ('Plush Carpet', '长绒地毯'),
  ('Polyurethane', '聚氨酯'),
  ('Portable AC', '便携式空调'),
  ('Portable Cooktops', '便携式炉灶'),
  ('Portable Dishwashers', '便携式洗碗机'),
  ('Portable Generators', '便携式发电机'),
  ('Pot Fillers', '锅具注水龙头'),
  ('Pots & Planters', '花盆与种植箱'),
  ('Power Drills', '电钻'),
  ('Power Tool Combos', '电动工具组合套装'),
  ('Prefinished Hardwood', '预涂装硬木地板'),
  ('Pressure Tanks', '压力罐'),
  ('Programmable Thermostats', '可编程温控器'),
  ('Propane & Solar Freezers', '丙烷与太阳能冷柜'),
  ('Pruners', '修枝剪'),
  ('Pull-Down Faucets', '下拉式龙头'),
  ('Pull-Out Faucets', '抽拉式龙头'),
  ('Pull-Out Organizers', '抽拉收纳架'),
  ('Push Mowers', '手推割草机'),
  ('PVC Pipe', 'PVC管'),
  ('Quarter Round', '四分之一圆线条'),
  ('Radiant Barrier', '隔热反射层'),
  ('Rakes', '耙子'),
  ('Range Parts', '炉灶配件'),
  ('Ratchets', '棘轮扳手'),
  ('Ready-Mix Concrete', '预拌混凝土'),
  ('Rebates & Offers', '返利与优惠'),
  ('Recessed Lights', '嵌入式灯'),
  ('Reducers', '过渡收边条'),
  ('Refrigerator Parts', '冰箱配件'),
  ('Remote 4 drones', '4遥控无人机'),
  ('Remote 6 drones', '6遥控无人机'),
  ('Riding Mowers', '骑乘式割草机'),
  ('Robe Hooks', '浴袍挂钩'),
  ('Robotic Mowers', '机器人割草机'),
  ('Roof Vents', '屋顶通风口'),
  ('Rope', '绳索'),
  ('Safes', '保险箱'),
  ('Sanders & Grinders', '砂光机与角磨机'),
  ('Saw Blades', '锯片'),
  ('Saws & Blades', '锯具与锯片'),
  ('Scaffolding', '脚手架'),
  ('Sealants', '密封胶'),
  ('Security Cables', '安全钢缆'),
  ('Security Cameras', '安防摄像头'),
  ('Seeds & Plants', '种子与植物'),
  ('Shovels', '铲子'),
  ('Shower Enclosures', '淋浴房'),
  ('Shower Kits', '淋浴套件'),
  ('Shower Pans', '淋浴底盘'),
  ('Shut-Off Valves', '截止阀'),
  ('Single Sink Vanities', '单盆浴室柜'),
  ('Sinks & Drains', '水槽与排水'),
  ('Slate', '板岩'),
  ('Slide-In Ranges', '嵌入式滑入炉灶'),
  ('Sliding Shower Doors', '推拉淋浴门'),
  ('Small Space Freezers', '小空间冷柜'),
  ('Smart Hubs', '智能网关'),
  ('Smart Locks', '智能门锁'),
  ('Smart Outlets', '智能插座'),
  ('Smart Thermostats', '智能温控器'),
  ('Smart Toilets', '智能马桶'),
  ('Snow Blowers', '吹雪机'),
  ('Socket Sets', '套筒套装'),
  ('Soffits & Fascia', '檐底板与封檐板'),
  ('Softeners', '软水机'),
  ('Softwood Plywood', '软木胶合板'),
  ('Spacers', '瓷砖定位器'),
  ('Spray Foam', '喷涂泡沫'),
  ('Squares', '角尺'),
  ('Standby Generators', '备用发电机'),
  ('Staplers', '订书枪'),
  ('Steel Studs', '轻钢龙骨'),
  ('Step Ladders', '人字梯'),
  ('Stone Backsplash', '石材挡水板'),
  ('Storage Bins', '储物箱'),
  ('Storage Cabinets', '储物柜'),
  ('Storage Containers', '收纳容器'),
  ('Storage Racks', '储物架'),
  ('String Trimmers', '打草机'),
  ('Suite Deals', '套装优惠'),
  ('Sump Pumps', '污水泵'),
  ('T-Molding', 'T型压条'),
  ('Table Saws', '台锯'),
  ('Tape', '胶带'),
  ('Tape Measures', '卷尺'),
  ('Thermostats & Controls', '温控器与控制器'),
  ('Tool Cabinets', '工具柜'),
  ('Tool Sets', '工具套装'),
  ('Towel Bars', '毛巾杆'),
  ('Travertine', '洞石'),
  ('Treated Lumber', '防腐木'),
  ('Trowels', '抹刀'),
  ('Tub & Shower Combos', '浴缸淋浴组合'),
  ('Tub Fillers', '浴缸龙头'),
  ('Two-Piece Toilets', '分体马桶'),
  ('Under Cabinet Lights', '柜底灯'),
  ('Under Sink Filters', '厨下过滤器'),
  ('Undermount Sinks', '台下盆'),
  ('Upright Freezers', '立式冷柜'),
  ('Utility Cabinets', '多用途柜'),
  ('Utility Hooks', '多用途挂钩'),
  ('Utility Knives', '美工刀'),
  ('Vegetable Seeds', '蔬菜种子'),
  ('Ventilation Fans with Light', '带灯通风扇'),
  ('Vessel Sinks', '台盆'),
  ('Video Doorbells', '可视门铃'),
  ('Vinyl Gutters', '乙烯基檐槽'),
  ('Vinyl Sheet', '乙烯基卷材'),
  ('Voice Control', '语音控制'),
  ('Wall Anchors', '墙锚'),
  ('Wall Cabinets', '吊柜'),
  ('Wall Heaters', '壁挂取暖器'),
  ('Wall Systems', '墙面收纳系统'),
  ('Wall-Mounted Sinks', '壁挂洗手盆'),
  ('Wall-Mounted Vanities', '壁挂浴室柜'),
  ('Washer Parts', '洗衣机配件'),
  ('Water Filter', '净水滤芯'),
  ('Water Filters', '净水滤芯'),
  ('Water Filtration', '净水过滤'),
  ('Watering Timers', '浇水定时器'),
  ('Waterproof Membrane', '防水膜'),
  ('Weed Killer', '除草剂'),
  ('Well Pumps', '井泵'),
  ('Whole House Fans', '全屋风扇'),
  ('Window AC', '窗式空调'),
  ('Window AC Units', '窗式空调'),
  ('Wire Accessories', '金属网架配件'),
  ('Wire Baskets', '金属网篮'),
  ('Wire Shelf Units', '金属网置物架'),
  ('Wireless Doorbells', '无线门铃'),
  ('Wood Floor Stain', '木地板着色剂'),
  ('Wood Stoves', '燃木炉'),
  ('Wrench Sets', '扳手套装'),
  ('Zero-Turn Mowers', '零转弯割草机')
)
update public.pc_product_categories category
set
  name = translated.zh_name,
  name_en = translated.english_name,
  updated_at = now()
from translated_category_names translated
where category.code like 'storefront:%'
  and coalesce(nullif(category.name_en, ''), category.name) = translated.english_name;
