-- Remote-only migration placeholder.
-- This file exists to align local migration history with the linked Supabase
-- project, which already has migration version 20260321053010 applied.
-- The actual schema change was created directly on the remote project.
