-- Restore bilingual Chinese/English names for the unified storefront Product Center tree.
-- The canonical tree remains storefront:*; only display names are localized.

with translated_category_names(english_name, zh_name) as (
  values
  ('ABS Pipe & Fittings', 'ABS管'),
  ('AC Rated Laminate', 'AC等级地板'),
  ('Adirondack Chairs', '阿迪朗达克椅'),
  ('Air Conditioners', '空调'),
  ('Air Handlers', '空气处理器'),
  ('Air Purifiers', '空气净化器'),
  ('Air Purifiers & Humidifiers', '空气净化器与加湿器'),
  ('Alcove Bathtubs', '嵌入式浴缸'),
  ('Anchors', '膨胀螺丝'),
  ('Appliance Parts & Accessories', '家电配件与附件'),
  ('Appliance Promotions', '家电促销'),
  ('Appliances', '家用电器'),
  ('Area Rugs', '区域地毯'),
  ('Armoires', '衣柜'),
  ('Attic Ventilation', '阁楼通风'),
  ('Awning Windows', '上悬窗'),
  ('Backsplash', '后挡板'),
  ('Backsplashes', '挡水板'),
  ('Ball Valves', '球阀'),
  ('Bamboo Flooring', '竹地板'),
  ('Bar Stools', '吧椅'),
  ('Barn Doors', '谷仓门'),
  ('Baseboards', '踢脚线'),
  ('Bath', '卫浴洁具'),
  ('Bath Accessories', '卫浴配件'),
  ('Bathroom Accessories', '卫浴配件'),
  ('Bathroom Cabinets', '浴室柜'),
  ('Bathroom Faucets', '浴室龙头'),
  ('Bathroom Hardware', '卫浴五金'),
  ('Bathroom Lighting', '浴室照明'),
  ('Bathroom Mirrors', '镜子'),
  ('Bathroom Sinks', '浴室洗手盆'),
  ('Bathroom Vanities', '浴室柜'),
  ('Bathroom Ventilation', '浴室通风'),
  ('Bathtub Accessories', '浴缸配件'),
  ('Bathtubs', '浴缸'),
  ('Bathtubs & Showers', '浴缸与淋浴'),
  ('Bay & Bow Windows', '凸窗'),
  ('Bedroom Furniture', '卧室家具'),
  ('Bedroom Sets', '卧室套装'),
  ('Beds', '床'),
  ('Bell Shades', '钟形灯罩'),
  ('Bench Cushions', '长凳垫'),
  ('Bidets & Bidet Seats', '智能坐便器'),
  ('Bifold Doors', '折叠门'),
  ('Bins & Containers', '收纳箱与容器'),
  ('Blinds', '百叶窗'),
  ('Blinds & Shades', '百叶窗'),
  ('Blowers', '吹风机'),
  ('Bolts', '螺栓'),
  ('Brushes & Rollers', '刷子滚筒'),
  ('Buffets', '餐边柜'),
  ('Building Materials', '建筑材料'),
  ('Bungee Cords', '弹力绳'),
  ('Butcher Block Countertops', '实木台面'),
  ('Cabinet & Furniture Paint', '橱柜漆'),
  ('Cabinet Hardware', '橱柜五金'),
  ('Cabinet Hinges', '橱柜铰链'),
  ('Cabinet Knobs', '橱柜把手'),
  ('Cabinet Pulls', '橱柜拉手'),
  ('Cabinets', '橱柜'),
  ('Cable Ties & Accessories', '扎带'),
  ('Candles', '蜡烛'),
  ('Canopies', '遮阳棚'),
  ('Cantilever Umbrellas', '悬臂伞'),
  ('Canvas Art', '帆布画'),
  ('Carpet', '地毯'),
  ('Carpet & Carpet Tile', '地毯与方块地毯'),
  ('Carpet Rolls', '卷材地毯'),
  ('Carpet Tiles', '地毯砖'),
  ('Casement Windows', '平开窗'),
  ('Catches & Latches', '门扣'),
  ('Ceiling Fans', '吊扇'),
  ('Ceiling Fans with Lights', '带灯吊扇'),
  ('Ceiling Hooks', '顶钩'),
  ('Ceiling Lights', '吸顶灯'),
  ('Ceiling Paint', '天花板漆'),
  ('Cement', '水泥'),
  ('Ceramic Tile', '陶瓷砖'),
  ('CFL Bulbs', '节能灯泡'),
  ('Chain Link Fencing', '链环栅栏'),
  ('Chains', '链条'),
  ('Chains & Ropes', '链条绳索'),
  ('Chainsaws', '电锯'),
  ('Chair Cushions', '椅垫'),
  ('Chalkboard Paint', '黑板漆'),
  ('Chandeliers', '枝形吊灯'),
  ('Chandeliers & Pendants', '吊灯与垂灯'),
  ('Charcoal Grills', '炭烤炉'),
  ('Check Valves', '止回阀'),
  ('Chimineas', '户外壁炉'),
  ('China Cabinets', '餐具柜'),
  ('Circuit Breakers', '断路器'),
  ('Circuit Breakers & Panels', '断路器'),
  ('Clocks', '时钟'),
  ('Closet Organization', '衣柜整理'),
  ('Closet Systems', '衣柜系统'),
  ('Coffee Tables', '茶几'),
  ('Concrete & Cement', '混凝土水泥'),
  ('Concrete Blocks', '混凝土砌块'),
  ('Concrete Mix', '混凝土'),
  ('Conduit', '线管'),
  ('Cooktops', '炉灶'),
  ('Copper Pipe & Fittings', '铜管'),
  ('Countertops', '台面'),
  ('Crystal Chandeliers', '水晶吊灯'),
  ('Curtains', '窗帘'),
  ('Deadbolts', '插销锁'),
  ('Deck & Porch Paint', '甲板漆'),
  ('Deck Boxes', '露台收纳箱'),
  ('Decor & Furniture', '装饰与家具'),
  ('Decorative Accents', '装饰摆件'),
  ('Decorative Bowls', '装饰碗'),
  ('Decorative Pillows', '装饰枕'),
  ('Decorative Storage', '装饰收纳盒'),
  ('Dehumidifiers', '除湿机'),
  ('Dimensional Lumber', '规格材'),
  ('Dimmers', '调光器'),
  ('Dining Chairs', '餐椅'),
  ('Dining Room Furniture', '餐厅家具'),
  ('Dining Tables', '餐桌'),
  ('Dishwashers', '洗碗机'),
  ('Door Closers', '闭门器'),
  ('Door Frames', '门框'),
  ('Door Frames & Jambs', '门框与门套'),
  ('Door Handles', '门把手'),
  ('Door Hardware', '门五金'),
  ('Door Hardware & Locks', '门五金与门锁'),
  ('Door Jambs', '门套'),
  ('Door Knobs', '门把手'),
  ('Door Levers', '门拉手'),
  ('Door Locks', '门锁'),
  ('Door Seals', '门密封件'),
  ('Door Sweeps', '门底密封条'),
  ('Door Trim', '门线条'),
  ('Doorbells & Intercoms', '门铃与对讲机'),
  ('Doors & Windows', '门窗'),
  ('Double Hung Windows', '双悬窗'),
  ('Drain Cleaning', '排水清洁'),
  ('Drapes', '帷幔'),
  ('Drawer Slides', '抽屉滑轨'),
  ('Dressers', '梳妆柜'),
  ('Drills', '电钻'),
  ('Drip Irrigation', '滴灌系统'),
  ('Drone', '无人机'),
  ('Drop Cloths', '防尘布'),
  ('Drum Shades', '鼓形灯罩'),
  ('Dryers', '烘干机'),
  ('Drywall', '石膏板'),
  ('Drywall & Accessories', '石膏板与配件'),
  ('Drywall Panels', '石膏板材'),
  ('Drywall Tape', '石膏板胶带'),
  ('Drywall Tools', '石膏板工具'),
  ('Ducts & Vents', '风管通风口'),
  ('Dust Masks & Respirators', '防尘口罩'),
  ('Ear Protection', '听力保护'),
  ('Electric Heaters', '电加热器'),
  ('Electrical', '电气照明'),
  ('Electrical Boxes & Covers', '电气盒'),
  ('Electrical Wire', '电线'),
  ('Empire Shades', '帝国形灯罩'),
  ('Engineered Hardwood', '工程木'),
  ('Entry Doors', '入户门'),
  ('Exhaust Fans', '排气扇'),
  ('Extension Cords', '延长线'),
  ('Extension Cords & Power Strips', '延长线与插线板'),
  ('Exterior Doors', '外门'),
  ('Exterior Paint', '外墙涂料'),
  ('Fan Accessories', '风扇配件'),
  ('Fans', '风扇'),
  ('Fasteners', '紧固件'),
  ('Faucet Parts & Repair', '龙头配件'),
  ('Faucet Repair Parts', '龙头维修'),
  ('Faucets', '水龙头'),
  ('Faucets & Fixtures', '龙头与洁具'),
  ('Fence Posts & Rails', '栅栏柱'),
  ('Fencing', '围栏'),
  ('Fiber Cement Siding', '纤维水泥板'),
  ('Fiberglass Insulation', '玻璃纤维保温'),
  ('Fire Pits & Fireplaces', '火盆与户外壁炉'),
  ('Fire Tables', '火炉桌'),
  ('Fireplaces & Stoves', '壁炉与炉具'),
  ('Flashing', '泛水板'),
  ('Floor Lamps', '落地灯'),
  ('Floor Molding & Trim', '地板线条与收边'),
  ('Floor Refinishing Products', '地板翻新产品'),
  ('Flooring', '地板地材'),
  ('Flooring Accessories', '地板配件'),
  ('Flooring Adhesives', '胶粘剂'),
  ('Flooring Tools & Accessories', '地板工具与配件'),
  ('Flooring Underlayment', '地板垫层'),
  ('Flush Mount', '贴顶灯'),
  ('Foam Insulation', '泡沫保温'),
  ('Fountains', '喷泉'),
  ('Framed Art', '装框画'),
  ('Freestanding Bathtubs', '独立式浴缸'),
  ('Freezers & Ice Makers', '冷柜与制冰机'),
  ('French Doors', '法式对开门'),
  ('Front Doors', '前门'),
  ('Full View Storm Doors', '全景防风门'),
  ('Furnaces', '熔炉'),
  ('Furnaces & Heaters', '暖炉与取暖器'),
  ('Furniture Hardware', '家具五金'),
  ('Fuses', '保险丝'),
  ('Garage Cabinets', '车库柜'),
  ('Garage Door Openers', '车库门开门器'),
  ('Garage Door Parts', '车库门配件'),
  ('Garage Doors', '车库门'),
  ('Garage Storage', '车库收纳'),
  ('Garbage Disposals', '垃圾处理器'),
  ('Garbage Disposals & Accessories', '垃圾处理器及配件'),
  ('Garden Edging', '花园边界'),
  ('Garden Hoses', '园艺软管'),
  ('Garden Statues', '花园雕像'),
  ('Gas Fire Pits', '燃气火盆'),
  ('Gas Grills', '燃气烤炉'),
  ('Gate Hardware', '门闸五金'),
  ('Gate Valves', '闸阀'),
  ('Gazebos', '凉亭'),
  ('Gazebos & Pergolas', '凉亭与花架'),
  ('Generators', '发电机'),
  ('GFCI Outlets', '漏电保护插座'),
  ('Glass Backsplash', '玻璃后挡板'),
  ('Granite Countertops', '花岗岩台面'),
  ('Grills & Outdoor Cooking', '烧烤与户外烹饪'),
  ('Grinders', '磨光机'),
  ('Grout', '灌浆料'),
  ('Gutters & Accessories', '排水沟'),
  ('Gutters & Drainage', '檐槽与排水'),
  ('Hammers', '锤子'),
  ('Hammers & Nail Guns', '锤子与钉枪'),
  ('Hand Tools', '手动工具'),
  ('Hangers', '衣架'),
  ('Hard Hats', '安全帽'),
  ('Hardware', '五金工具'),
  ('Hardwood', '硬木'),
  ('Hardwood Flooring', '实木地板'),
  ('Heat Pumps', '热泵'),
  ('Heaters', '加热器'),
  ('Heating & Cooling', '暖通空调'),
  ('Heating, Cooling & Air Quality', '供暖制冷与空气质量'),
  ('Hinges', '铰链'),
  ('Holiday Decor', '节日装饰'),
  ('Home Automation', '家居自动化'),
  ('Home Decor', '家居装饰'),
  ('Hooks & Storage', '挂钩收纳'),
  ('Hose Reels', '软管卷盘'),
  ('House & Siding Paint', '房屋外墙漆'),
  ('HVAC Parts & Accessories', 'HVAC配件'),
  ('HVAC Systems', 'HVAC系统'),
  ('Impact Drivers', '冲击起子'),
  ('Indoor Fans', '室内风扇'),
  ('Indoor Lighting', '室内照明'),
  ('Indoor Sconces', '室内壁灯'),
  ('Insulation', '保温隔热'),
  ('Interior Doors', '室内门'),
  ('Interior Paint', '内墙涂料'),
  ('Island Lights', '岛台灯'),
  ('Joint Compound', '接缝腻子'),
  ('Junction Boxes', '接线盒'),
  ('Kitchen', '厨房设备'),
  ('Kitchen Accessories', '厨房配件'),
  ('Kitchen Appliances', '厨房电器'),
  ('Kitchen Cabinets', '厨房橱柜'),
  ('Kitchen Faucets', '厨房龙头'),
  ('Kitchen Hardware', '厨房五金'),
  ('Kitchen Islands & Carts', '厨房岛台与推车'),
  ('Kitchen Lighting', '厨房照明'),
  ('Kitchen Packages', '厨房套装'),
  ('Kitchen Sinks', '厨房水槽'),
  ('Laminate Countertops', '层压台面'),
  ('Laminate Flooring', '强化地板'),
  ('Lamp Shades', '灯罩'),
  ('Landscape Lighting', '景观照明'),
  ('Landscaping', '景观美化'),
  ('Laundry', '洗衣设备'),
  ('Laundry Accessories', '洗衣配件'),
  ('Laundry Cabinets', '洗衣柜'),
  ('Lawn & Garden', '园艺花园'),
  ('Lawn Mowers', '割草机'),
  ('LED Bulbs', 'LED 灯泡'),
  ('LED Strip Lights', 'LED灯带'),
  ('Levels', '水平仪'),
  ('Light Bulbs', '灯泡'),
  ('Light Switches', '开关'),
  ('Lighting & Ceiling Fans', '照明灯具'),
  ('Lighting & Fans', '照明与风扇'),
  ('Lighting Controllers', '照明控制器'),
  ('Lighting Fixtures', '照明灯具'),
  ('Living Room Furniture', '客厅家具'),
  ('Load Centers', '配电箱'),
  ('Lounge Chairs', '躺椅'),
  ('Loveseats', '双人沙发'),
  ('Lumber & Composites', '木材'),
  ('Luxury Vinyl Plank (LVP)', 'LVP豪华乙烯基'),
  ('Market Umbrellas', '市集伞'),
  ('Masonry Paint', '砌体漆'),
  ('MDF', 'MDF密度板'),
  ('Measuring & Layout Tools', '测量工具'),
  ('Medicine Cabinets', '药柜'),
  ('Metal Building Materials', '金属建材'),
  ('Microwaves', '微波炉'),
  ('Mirrors & Medicine Cabinets', '镜子与药柜'),
  ('Modern Pendants', '现代吊灯'),
  ('Monorail Systems', '单轨照明系统'),
  ('Mortar', '砂浆'),
  ('Mosaic Tile', '马赛克砖'),
  ('Mulch', '覆盖物'),
  ('Nail Guns', '射钉枪'),
  ('Nails', '钉子'),
  ('Natural Stone Flooring', '天然石材地板'),
  ('Natural Stone Tile', '天然石材'),
  ('Nightstands', '床头柜'),
  ('Nuts', '螺母'),
  ('OSB', 'OSB板材'),
  ('Outdoor Cushions', '户外坐垫'),
  ('Outdoor Décor', '户外装饰'),
  ('Outdoor Decorations', '户外装饰'),
  ('Outdoor Fans', '户外风扇'),
  ('Outdoor Fireplaces', '户外壁炉'),
  ('Outdoor Heating', '户外取暖'),
  ('Outdoor Lighting', '室外照明'),
  ('Outdoor Living', '户外生活'),
  ('Outdoor Power Equipment', '户外动力设备'),
  ('Outdoor Rugs', '户外地毯'),
  ('Outdoor Sconces', '户外壁灯'),
  ('Outdoor Sofas', '户外沙发'),
  ('Outdoor Storage', '户外收纳'),
  ('Outlet Boxes', '插座盒'),
  ('Outlets & Switches', '插座开关'),
  ('Paint', '涂料油漆'),
  ('Paint Supplies', '涂料用品'),
  ('Paint Trays & Liners', '油漆盘'),
  ('Painter''s Tape', '美纹纸胶带'),
  ('Panel Doors', '板式门'),
  ('Pantry Storage', '食品储藏收纳'),
  ('Path Lights', '路径灯'),
  ('Patio Doors', '庭院门'),
  ('Patio Furniture', '庭院家具'),
  ('Patio Heaters', '庭院取暖器'),
  ('Patio Sets', '庭院套装'),
  ('Patio Umbrellas', '庭院伞'),
  ('Pavers & Stepping Stones', '铺路石'),
  ('Pavilions', '亭阁'),
  ('Peel & Stick Backsplash', '自粘后挡板'),
  ('Pellet Grills', '颗粒烤炉'),
  ('Pendant Lights', '吊灯'),
  ('Pergolas', '花架'),
  ('PEX Pipe & Fittings', 'PEX管'),
  ('Photo Frames', '相框'),
  ('Pillow Sets', '抱枕套装'),
  ('Pipes & Fittings', '管道配件'),
  ('Planters', '花盆'),
  ('Plastic Shelving', '塑料货架'),
  ('Plastic Storage Bins', '塑料箱'),
  ('Playhouses', '儿童游戏屋'),
  ('Playsets & Trampolines', '游乐架与蹦床'),
  ('Pliers', '钳子'),
  ('Plumber''s Putty & Sealants', '水管密封胶'),
  ('Plumbing', '管道水暖'),
  ('Plumbing Repair', '管道维修'),
  ('Plywood', '胶合板'),
  ('Plywood & Sheathing', '胶合板与护墙板'),
  ('Pocket Doors', '推拉门'),
  ('Porcelain Tile', '瓷质砖'),
  ('Portable Heaters', '便携式取暖器'),
  ('Portable Heating', '便携加热器'),
  ('Post Lights', '柱头灯'),
  ('Power Tools', '电动工具'),
  ('Pressure Treated Lumber', '防腐木'),
  ('Pressure Washers', '高压清洗机'),
  ('Primer', '底漆'),
  ('Propane Heaters', '丙烷加热器'),
  ('Pumps & Tanks', '泵与储罐'),
  ('PVC Pipe & Fittings', 'PVC管'),
  ('Quartz Countertops', '石英台��'),
  ('Range Hoods', '抽油烟机'),
  ('Ranges', '烤箱炉灶'),
  ('Recessed Cans', '嵌入式灯筒'),
  ('Recessed Lighting', '嵌入式照明'),
  ('Recessed Trims', '嵌入式灯圈'),
  ('Recliners', '躺椅'),
  ('Reflective Insulation', '反射保温'),
  ('Refrigerators', '冰箱'),
  ('Retractable Screen Doors', '可伸缩纱门'),
  ('Retrofit Kits', '改装套件'),
  ('Robot & Drone', '机器人与无人机'),
  ('Robots', '机器人'),
  ('Roof Coating', '屋顶涂料'),
  ('Roof Underlayment', '防水层'),
  ('Roofing', '屋顶材料'),
  ('Roofing Materials', '屋面材料'),
  ('Ropes', '绳索'),
  ('Rug Pads', '地毯垫'),
  ('Rugs & Area Carpets', '地毯与区域毯'),
  ('Runner Rugs', '走廊毯'),
  ('Safety & Security', '安全与安防'),
  ('Safety Equipment', '安全设备'),
  ('Safety Glasses', '安全眼镜'),
  ('Sanders', '砂光机'),
  ('Saws', '电锯'),
  ('Screwdrivers', '螺丝刀'),
  ('Screws', '螺丝'),
  ('Sculptures', '雕塑摆件'),
  ('Seasonal Decor', '季节装饰'),
  ('Seasonal Wreaths', '季节花环'),
  ('Sectional Doors', '分段车库门'),
  ('Sectionals', '组合沙发'),
  ('Security Doors', '防盗门'),
  ('Security Systems', '安防系统'),
  ('Semi-Flush Mount', '半吸顶灯'),
  ('Shades', '遮光帘'),
  ('Sheds', '储物棚'),
  ('Sheet Vinyl', '卷材乙烯基'),
  ('Shelf Brackets', '搁板支架'),
  ('Shelving', '货架'),
  ('Shelving Units', '置物架'),
  ('Shingles', '瓦片'),
  ('Shoe Racks', '鞋架'),
  ('Shower Bases', '淋浴底盆'),
  ('Shower Caddies', '置物架'),
  ('Shower Doors', '淋浴门'),
  ('Shower Doors & Enclosures', '淋浴门与隔断'),
  ('Shower Heads', '淋浴花洒头'),
  ('Shower Panels', '淋浴隔板'),
  ('Shower Systems', '淋浴系统'),
  ('Showers', '淋浴花洒'),
  ('Shutoff Valves', '截止阀'),
  ('Shutters', '百叶窗板'),
  ('Siding', '外墙装饰'),
  ('Siding & Trim', '外墙板与装饰线条'),
  ('Sink Accessories', '水槽配件'),
  ('Sinks', '水槽洗手盆'),
  ('Skylights', '天窗'),
  ('Sliding Doors', '推拉门'),
  ('Sliding Windows', '推拉窗'),
  ('Smart Bulbs', '智能灯泡'),
  ('Smart Lighting', '智能照明'),
  ('Smart Switches', '智能开关'),
  ('Smokers', '烟熏炉'),
  ('Soap Dispensers', '皂液器'),
  ('Sofas', '沙发'),
  ('Soil & Amendments', '土壤'),
  ('Solid Hardwood', '纯实木'),
  ('Space Heaters', '空间加热器'),
  ('Specialty Bulbs', '特种灯泡'),
  ('Specialty Paint', '特殊涂料'),
  ('Spotlights', '射灯'),
  ('Spray Paint', '喷漆'),
  ('Sprinklers', '洒水器'),
  ('Storage & Organization', '存储收纳'),
  ('Storage Benches', '收纳长凳'),
  ('Storage Bins & Boxes', '储物箱'),
  ('Storage Drawers', '收纳抽屉'),
  ('Storage Totes', '手提箱'),
  ('Storm Doors', '防风门'),
  ('String Lights', '串灯'),
  ('Surge Protectors', '浪涌保护器'),
  ('Swing Sets', '秋千组合'),
  ('Table Lamps', '台灯'),
  ('Tank Water Heaters', '储水式热水器'),
  ('Tankless Water Heaters', '即热式热水器'),
  ('Thermostats', '温控器'),
  ('Throws', '毯子'),
  ('Tie-Downs', '捆绑带'),
  ('Tile Backsplash', '瓷砖后挡板'),
  ('Tile Flooring', '瓷砖地板'),
  ('Toilet Paper Holders', '纸巾架'),
  ('Toilet Repair Parts', '马桶配件'),
  ('Toilet Seats', '马桶座圈'),
  ('Toilets', '马桶'),
  ('Toilets & Bidets', '马桶与智能坐便器'),
  ('Toilets & Toilet Parts', '马桶与马桶配件'),
  ('Toilets & Toilet Seats', '马桶座便器'),
  ('Tool Bags', '工具包'),
  ('Tool Belts', '工具腰带'),
  ('Tool Boxes', '工具箱'),
  ('Tool Chests', '工具柜'),
  ('Tool Storage', '工具存储'),
  ('Tools', '工具设备'),
  ('Towel Bars & Hooks', '毛巾架'),
  ('Track & Rail Lighting', '轨道照明'),
  ('Track Heads', '轨道灯头'),
  ('Track Lighting Kits', '轨道灯套装'),
  ('Trampolines', '蹦床'),
  ('Transition Strips', '过渡条'),
  ('Trim & Door Paint', '装饰条漆'),
  ('Trim & Molding', '装饰条'),
  ('Trimmers & Edgers', '修剪机'),
  ('Tub & Shower Faucets', '浴缸淋浴龙头'),
  ('TV Stands', '电视柜'),
  ('Umbrella Bases', '伞座'),
  ('Underlayment', '地板垫'),
  ('Urinals', '小便器'),
  ('USB Outlets', 'USB插座'),
  ('Utility Faucets', '工用龙头'),
  ('Utility Sinks', '工用水槽'),
  ('Valances', '窗幔'),
  ('Valves', '阀门'),
  ('Valves & Manifolds', '阀门与分水器'),
  ('Vanities', '浴室柜'),
  ('Vanity Lights', '浴室镜前灯'),
  ('Vanity Tops', '台面'),
  ('Vases', '花瓶'),
  ('Ventilation', '通风换气'),
  ('Ventilation Fans', '通风扇'),
  ('Vinyl & Resilient Flooring', '乙烯基地板与弹性地板'),
  ('Vinyl Fencing', '乙烯基栅栏'),
  ('Vinyl Flooring', '乙烯基地板'),
  ('Vinyl Siding', '乙烯基壁板'),
  ('Vinyl Tile', '乙烯基瓷砖'),
  ('Wall Art', '墙面艺术'),
  ('Wall Art & Mirrors', '墙饰与镜子'),
  ('Wall Decals', '墙贴'),
  ('Wall Hooks', '墙钩'),
  ('Wall Mirrors', '墙镜'),
  ('Wall Outlets', '墙壁插座'),
  ('Wall Paint', '墙面漆'),
  ('Wall Plates', '面板'),
  ('Wall Sconces', '壁灯'),
  ('Wall Shelves', '墙面搁板'),
  ('Wall-Mounted Storage', '壁挂收纳'),
  ('Washer & Dryer Combos', '洗烘一体机'),
  ('Washers', '垫圈'),
  ('Water Heater Parts', '热水器配件'),
  ('Water Heaters', '热水器'),
  ('Watering & Irrigation', '灌溉系统'),
  ('Waterproof Laminate', '防水强化'),
  ('Weather Strip', '密封条'),
  ('Weather Stripping', '门窗密封条'),
  ('Weatherproofing & Flashing', '防水密封与泛水板'),
  ('Weatherstripping', '密封条'),
  ('Whirlpool Tubs', '按摩浴缸'),
  ('Wind Chimes', '风铃'),
  ('Window Handles', '窗把手'),
  ('Window Hardware', '窗户五金'),
  ('Window Locks', '窗锁'),
  ('Window Screens', '纱窗'),
  ('Window Treatments', '窗饰'),
  ('Windows', '窗户'),
  ('Windows & Doors', '门窗'),
  ('Wire & Cable', '电线电缆'),
  ('Wire Connectors', '接线端子'),
  ('Wire Shelving', '金属网架'),
  ('Wood Fencing', '木栅栏'),
  ('Wood Fire Pits', '木燃火盆'),
  ('Wood Shelving', '木质货架'),
  ('Wood Siding', '木质壁板'),
  ('Work Gloves', '工作手套'),
  ('Wrenches', '扳手'),
  ('Wrenches & Sockets', '扳手与套筒')
)
update public.pc_product_categories category
set
  name = translated.zh_name,
  name_en = translated.english_name,
  updated_at = now()
from translated_category_names translated
where category.code like 'storefront:%'
  and coalesce(nullif(category.name_en, ''), category.name) = translated.english_name;
