create temporary table tmp_seeded_promotion_products (
  id text primary key,
  category_id text not null,
  name text not null,
  model text not null,
  image text not null,
  price numeric not null,
  net_weight numeric not null,
  gross_weight numeric not null,
  units_per_carton numeric not null,
  carton_length numeric not null,
  carton_width numeric not null,
  carton_height numeric not null,
  carton_net_weight numeric not null,
  carton_gross_weight numeric not null,
  specifications jsonb not null,
  region_code text not null,
  front_tag text not null,
  promotion_label text not null,
  display_priority int not null,
  compare_at_price numeric not null,
  valid_until date not null,
  moq numeric not null,
  quantity_step numeric not null,
  stock_quantity numeric not null,
  fulfillment_status text not null,
  eta_text text not null,
  search_keywords_csv text not null
) on commit drop;

insert into tmp_seeded_promotion_products (
  id,
  category_id,
  name,
  model,
  image,
  price,
  net_weight,
  gross_weight,
  units_per_carton,
  carton_length,
  carton_width,
  carton_height,
  carton_net_weight,
  carton_gross_weight,
  specifications,
  region_code,
  front_tag,
  promotion_label,
  display_priority,
  compare_at_price,
  valid_until,
  moq,
  quantity_step,
  stock_quantity,
  fulfillment_status,
  eta_text,
  search_keywords_csv
)
values
  (
    'na-led-a19-4pk-soft-white',
    'electrical-light-bulbs-led-bulbs',
    'A19 LED Bulb 4-Pack Soft White',
    'LED-A19-4PK-27K',
    'https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?auto=format&fit=crop&w=1200&q=80',
    9.90,
    1.10,
    1.30,
    4,
    18,
    12,
    8,
    4.40,
    5.20,
    jsonb_build_object(
      'Brand', 'COSUN Lighting',
      'Color Temperature', '2700K',
      'Wattage', '9W',
      'Lumens', '800 lm',
      'Finish', 'Frosted',
      'Material', 'Aluminum + PC'
    ),
    'NA',
    'Special Buy',
    'Save 23%',
    1,
    12.90,
    date '2026-05-15',
    24,
    4,
    480,
    'available',
    '3-5 days',
    'LED light bulbs, A19 bulbs, soft white, 4 pack'
  ),
  (
    'na-solid-oak-hardwood-18sqft',
    'flooring-hardwood-flooring-solid-hardwood',
    'Solid Oak Hardwood Flooring 18 sq. ft.',
    'FLOOR-OAK-18SF',
    'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
    64.00,
    18.50,
    20.20,
    1,
    124,
    19,
    7,
    18.50,
    20.20,
    jsonb_build_object(
      'Brand', 'COSUN Floors',
      'Species', 'Oak',
      'Finish', 'Natural Matte',
      'Coverage', '18 sq. ft.',
      'Thickness', '18 mm',
      'Wear Layer', 'Solid hardwood'
    ),
    'NA',
    'Hot Deal',
    'Save 20%',
    2,
    79.90,
    date '2026-05-15',
    5,
    1,
    120,
    'limited',
    '5-7 days',
    'solid oak flooring, hardwood planks, natural matte'
  ),
  (
    'na-sectional-sofa-charcoal',
    'decor-and-furniture-living-room-furniture-sofas',
    'Modular Sectional Sofa Charcoal',
    'SOFA-SEC-CH-302',
    'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
    899.00,
    72.00,
    88.00,
    1,
    210,
    95,
    82,
    72.00,
    88.00,
    jsonb_build_object(
      'Brand', 'COSUN Home',
      'Material', 'Polyester Fabric',
      'Color', 'Charcoal',
      'Seats', '4',
      'Assembly', 'Easy assembly',
      'Cushion Fill', 'High-density foam'
    ),
    'NA',
    'Bundle',
    'Save $200',
    3,
    1099.00,
    date '2026-05-15',
    1,
    1,
    18,
    'available',
    '7-10 days',
    'sectional sofa, living room furniture, charcoal sofa'
  ),
  (
    'na-spf-2x4x8-dimensional-lumber',
    'building-materials-lumber-and-composites-dimensional-lumber',
    'SPF Dimensional Lumber 2 in. x 4 in. x 8 ft.',
    'LMBR-SPF-2X4X8',
    'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    4.60,
    5.80,
    6.10,
    200,
    244,
    10,
    5,
    1160.00,
    1220.00,
    jsonb_build_object(
      'Brand', 'COSUN Timber',
      'Wood Species', 'SPF',
      'Nominal Size', '2 x 4',
      'Length', '8 ft.',
      'Treatment Type', 'Kiln Dried',
      'Grade', '#2 and Better'
    ),
    'NA',
    'Best Value',
    'Save 21%',
    4,
    5.80,
    date '2026-05-15',
    200,
    20,
    3200,
    'available',
    '2-4 days',
    'dimensional lumber, 2x4 lumber, SPF lumber'
  );

insert into public.products (
  id,
  category_id,
  name,
  model,
  image,
  price,
  net_weight,
  gross_weight,
  units_per_carton,
  carton_length,
  carton_width,
  carton_height,
  carton_net_weight,
  carton_gross_weight,
  specifications,
  region_code,
  updated_at
)
select
  id,
  category_id,
  name,
  model,
  image,
  price,
  net_weight,
  gross_weight,
  units_per_carton,
  carton_length,
  carton_width,
  carton_height,
  carton_net_weight,
  carton_gross_weight,
  specifications,
  region_code,
  now()
from tmp_seeded_promotion_products
on conflict (id) do update set
  category_id = excluded.category_id,
  name = excluded.name,
  model = excluded.model,
  image = excluded.image,
  price = excluded.price,
  net_weight = excluded.net_weight,
  gross_weight = excluded.gross_weight,
  units_per_carton = excluded.units_per_carton,
  carton_length = excluded.carton_length,
  carton_width = excluded.carton_width,
  carton_height = excluded.carton_height,
  carton_net_weight = excluded.carton_net_weight,
  carton_gross_weight = excluded.carton_gross_weight,
  specifications = excluded.specifications,
  region_code = excluded.region_code,
  updated_at = now();

insert into public.product_publications (
  id,
  product_id,
  region_code,
  publish_type,
  publish_status,
  display_priority,
  promotion_label,
  front_tag,
  website_note,
  updated_at
)
select
  id || '-na-website-publication',
  id,
  region_code,
  'deal',
  'published',
  display_priority,
  promotion_label,
  front_tag,
  'Seeded deal product for storefront recovery.',
  now()
from tmp_seeded_promotion_products
on conflict (product_id, region_code) do update set
  publish_type = excluded.publish_type,
  publish_status = excluded.publish_status,
  display_priority = excluded.display_priority,
  promotion_label = excluded.promotion_label,
  front_tag = excluded.front_tag,
  website_note = excluded.website_note,
  updated_at = now();

insert into public.product_prices (
  id,
  product_id,
  region_code,
  currency,
  unit,
  sale_price,
  compare_at_price,
  price_type,
  valid_from,
  valid_until,
  status,
  updated_at
)
select
  id || '-na-usd-website',
  id,
  region_code,
  'USD',
  'pc',
  price,
  compare_at_price,
  'website',
  date '2026-04-29',
  valid_until,
  'active',
  now()
from tmp_seeded_promotion_products
on conflict (product_id, region_code, currency, price_type) do update set
  unit = excluded.unit,
  sale_price = excluded.sale_price,
  compare_at_price = excluded.compare_at_price,
  valid_from = excluded.valid_from,
  valid_until = excluded.valid_until,
  status = excluded.status,
  updated_at = now();

insert into public.product_fulfillment (
  id,
  product_id,
  region_code,
  moq,
  quantity_step,
  stock_quantity,
  stock_unit,
  eta_text,
  fulfillment_status,
  updated_at
)
select
  id || '-na-fulfillment',
  id,
  region_code,
  moq,
  quantity_step,
  stock_quantity,
  'pc',
  eta_text,
  fulfillment_status,
  now()
from tmp_seeded_promotion_products
on conflict (product_id, region_code) do update set
  moq = excluded.moq,
  quantity_step = excluded.quantity_step,
  stock_quantity = excluded.stock_quantity,
  stock_unit = excluded.stock_unit,
  eta_text = excluded.eta_text,
  fulfillment_status = excluded.fulfillment_status,
  updated_at = now();

insert into public.product_assets (
  id,
  product_id,
  asset_type,
  asset_url,
  title,
  alt_text,
  sort_order,
  quality_status
)
select
  id || '-main-asset',
  id,
  'main',
  image,
  name,
  name,
  10,
  'approved'
from tmp_seeded_promotion_products
on conflict (id) do update set
  asset_url = excluded.asset_url,
  title = excluded.title,
  alt_text = excluded.alt_text,
  quality_status = excluded.quality_status;

insert into public.product_search_index (
  product_id,
  search_title,
  search_keywords,
  brand,
  model_number,
  internet_sku,
  category_path,
  updated_at
)
select
  id,
  name,
  string_to_array(search_keywords_csv, ', '),
  specifications->>'Brand',
  model,
  model,
  category_id,
  now()
from tmp_seeded_promotion_products
on conflict (product_id) do update set
  search_title = excluded.search_title,
  search_keywords = excluded.search_keywords,
  brand = excluded.brand,
  model_number = excluded.model_number,
  internet_sku = excluded.internet_sku,
  category_path = excluded.category_path,
  updated_at = now();

insert into public.promotion_campaigns (
  id,
  region_code,
  name,
  type,
  start_date,
  end_date,
  headline,
  description,
  cta_text,
  banner_color,
  product_ids,
  created_at
)
values (
  'campaign-special-offer-in-may-202604',
  'NA',
  'SPECIAL OFFER IN MAY',
  'weekly',
  date '2026-04-27',
  date '2026-05-15',
  'ALL FOR YOUR BENEFITS',
  'PINK SEASON IS COMING !',
  'Shop Now',
  'from-red-600 to-orange-500',
  array[
    'na-led-a19-4pk-soft-white',
    'na-solid-oak-hardwood-18sqft',
    'na-sectional-sofa-charcoal',
    'na-spf-2x4x8-dimensional-lumber'
  ],
  now()
)
on conflict (id) do update set
  region_code = excluded.region_code,
  name = excluded.name,
  type = excluded.type,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  headline = excluded.headline,
  description = excluded.description,
  cta_text = excluded.cta_text,
  banner_color = excluded.banner_color,
  product_ids = excluded.product_ids,
  updated_at = now();
